### ISSUE TITLE
Responsive?

### ISSUE THREAD

**Issue by paolavness** [video-react/video-react#10]
### Issue description
Not sure its an issue.... How to make this responsive - ie, respond with automatic scaling to screen size, whether on mobile, tablet, or resizing browser on laptop/desktop.

Thank you!
Paola

**Comment by JimLiu** [comment]
It's responsive by default.
Check the document in : https://video-react.github.io/components/player/
The player has a property named `fluid`, it's true by default, in fluid mode, it’s 100% wide all the time, the height will be calculated by the video's ratio.

**Comment by paolavness** [comment]
D'oh! Thank you I'll check this out.
