### ISSUE TITLE
Large file,HttpStatus Code 206

### ISSUE THREAD

**Issue by MuNaiYi520** [video-react/video-react#103]
### Issue description
When I used this player to play 40MB video files, there was no error, but when I played the 130MB video file, I made a mistake. The error message was HttpStatus Code 206. How do I solve this problem?
- version `65.0.3325.181`
- browser: `google brower `
![image](https://user-images.githubusercontent.com/7043494/38862939-de6c9fd0-4268-11e8-8557-bd6d9936b002.png)

**Comment by JimLiu** [comment]
206 is not an error code, it means it needs to download the video form middle of the file.  and your server does not support it.

You can use IIS to serve static files, it supports 206.

This is not a video-react issue.
