### ISSUE TITLE
Player seems to ignore width and height attributes

### ISSUE THREAD

**Issue by rahenri** [video-react/video-react#106]
### Issue description

- version: latest
- browser: latest chrome

### Steps to reproduce issue

Set the width and height attribute on the Player component, the result is that the width and height are ignore and the player occupies all space available. Alternatively, I tried putting it in a container of the size that I want. That will force the player to be of that size, except it doesn't seem to work well with unusual aspect ratios, such as square videos from instagram.

**Comment by JimLiu** [comment]
Did you set `fluid` to `false`?

**Comment by rahenri** [comment]
That does the trick! Should have read those docs more carefully. Thank you!

**Comment by JimLiu** [comment]
Document updated
