### ISSUE TITLE
isTypeEqual & bundled lib issue

### ISSUE THREAD

**Issue by rogaldh** [video-react/video-react#109]
Hello there.
0.10+ version got [ability to output](https://github.com/video-react/video-react/blob/v0.10.1/src/utils/index.js#L82) children elements at ControlBar according to `displayName`. But since 0.9.4 there is [no `prebuild`](https://github.com/video-react/video-react/blob/v0.8.10/package.json#L14) step at package.json. In this case all later versions (since 0.8.10) at NPM are a bit broken (can't get access to MenuButton for ex.).

0.10.6 got these scripts back according to repo. But there is no 0.10.6 at NPM. What's a current status of repo?

P.S.: `isTypeEqual`'ll help a lot actually but the lack of lib ruins compatibility. I might use 0.8.10 but solutions are tricky enough : ) :crutch

**Comment by JimLiu** [comment]
sorry something was wrong with my script, I published v10.0.7, please help verify it.
let me know if there is any problem.

I'll close this ticket.

Thanks

**Comment by rogaldh** [comment]
Seems ok. Cheers
