### ISSUE TITLE
How to put the player fullscreen onstart

### ISSUE THREAD

**Issue by Alhydra** [video-react/video-react#111]
### Issue description

- version `#0.10.4`
- browser: `All`

Hello Guys, I really like your project so much,

i have a small problem, I cannot find a way to put the video player to full screen on video has started, I want it to be full screen automatically when the video is loaded.

**Comment by JimLiu** [comment]
document: https://video-react.js.org/components/player/
demo: https://codesandbox.io/s/6y46x3oxwk

```jsx
import React, { Component } from "react";
import { render } from "react-dom";
import Hello from "./Hello";
import { Player } from "video-react";
import "video-react/dist/video-react.css";

const styles = {
  fontFamily: "sans-serif",
  textAlign: "center"
};

class App extends Component {
  componentDidMount() {
    console.log(this.player);
    this.player.toggleFullscreen();
  }

  render() {
    return (
      <div style={styles}>
        <Hello name="Video React" />
        <h2>
          The web video player built from the ground up for an HTML5 world using
          React library. {"\u2728"}
        </h2>
        <Player
          ref={c => {
            this.player = c;
          }}
          playsInline
          poster="https://video-react.js.org/assets/poster.png"
        >
          <source
            src="https://media.w3.org/2010/05/sintel/trailer_hd.mp4"
            type="video/mp4"
          />
        </Player>
      </div>
    );
  }
}

render(<App />, document.getElementById("root"));

```

**Comment by kalwaniyash** [comment]
This breaks for me, it throws an error `fullscreen error`.
Can't even find `toggleFullscreen` function in the ref.

**Comment by williamzhou0812** [comment]
Under Node-module that you find “ video-react “ -> “ reducers” -> open “ player.js” 
 
and  Change / ADD code  isFullscreen: true 
 
___ Code line 93
 
   case _video.PLAY:
     return (0, _objectSpread2["default"])({}, state, action.videoProps, {
       ended: false,
       paused: false,
       autoPaused: false,
       isFullscreen: true,  // add code here
       waiting: false,
       hasStarted: true
     });

**Comment by jacky-0000** [comment]
Unhandled Rejection (TypeError): fullscreen error
