### ISSUE TITLE
Styling is not working

### ISSUE THREAD

**Issue by axwack** [video-react/video-react#112]
### Issue description
The styling and the importing is not as documented in the  github. Importing .scss does not work. 

- version `#x.x.x`
- browser: Crhome

### Steps to reproduce

import "./styles/scss/video-react.scss";

### Expected behaviour
Styling and buttons should be overlays on the screen

Regular HTML buttons show up.

### Demo
You can fork from this template and add your code
https://codesandbox.io/s/2v95wlpvjj

**Comment by axwack** [comment]
I used the Sandbox and this worked. 
import 'video-react/dist/video-react.css';

**Comment by JimLiu** [comment]
@blueyestar 
The scss file locates at `node_modules/video-react/dist/video-react.css`, but how to import it depends on your config of webpack or rollup or sass

**Comment by Sbphillips19** [comment]
If I follow directions and use css and import it in my component it works fine:

`import "video-react/dist/video-react.css";`

However if I try to implement in my scss files then I am having issues, where it doesn't do anything:

`@import '~video-react/styles/scss/video-react';`

I have tried using a path to node modules instead but same thing.  I can see the path matches and if too many ../ for example then it throws can't find error as expected.   Will just go with css now, but wondering if anyone else has any issues?
