### ISSUE TITLE
WMV File not working

### ISSUE THREAD

**Issue by dholakiyaankit** [video-react/video-react#115]
### Issue description
I checked with WMV, its not working. Is it because of the chrome compability?
- version `#0.10.5`
- browser: `Chrome- 66.0`

### Steps to reproduce issue
```
<Player><source src="http://www.lehman.edu/faculty/hoffmann/itc/techteach/video/Video2.WMV" />
                                </Player>
```

**Comment by JimLiu** [comment]
that's out of our control
FYI:
https://stackoverflow.com/questions/4459891/how-to-play-wmv-files-in-html5-video-player
