### ISSUE TITLE
Is this video-react.scss require necessary?

### ISSUE THREAD

**Issue by mcclowes** [video-react/video-react#117]
`video-react.scss` is imported in n lib > index.js:

```
118    require('../styles/scss/video-react.scss');
```

Is this import necessary, given the user should be importing the styles themselves? Throws up issues with webpack if you haven't included an SCSS loader, etc.

**Comment by mcclowes** [comment]
Thanks man :)

**Comment by JimLiu** [comment]
Removed in 0.10.9
