### ISSUE TITLE
Multiple source video

### ISSUE THREAD

**Issue by JulienHe** [video-react/video-react#12]
### Issue description

- version `#0.6.3`
- browser: `Chrome`

### Steps to reproduce issue
I implemented the solution to have multiple video in my component : https://github.com/video-react/video-react/wiki/Components#video. Can you give more advise or the entire code? I try it but it's not working.

Also, is it possible to decide the order of the fallback?

### Expected behaviour
The snippet should work

### Actual behaviour
The snippet is not working

**Comment by JimLiu** [comment]
Sorry the document is out of date, please check this:
https://video-react.github.io/

And I'll update the wiki later.

**Comment by JulienHe** [comment]
@JimLiu Can you update the Wiki please? We really want to use video-react, there is only this issue who block us. Thanks!

**Comment by JimLiu** [comment]
Hi @JulienHe 

Did you mean the document about HLSSource?

I deleted the wiki, and merge the content to the document site.

There is a sample on how to add a HLS source to video-react, but there is no Offical HLSSource for video-react.
