### ISSUE TITLE
Recommended usage example for new "refs" method in React 16.3.x

### ISSUE THREAD

**Issue by jfrux** [video-react/video-react#120]
Just curious if anyone has any recommended methods on implementing the examples from the website with the new refs in React 16.3.x...

Haven't had time to dig deep into them yet.

**Comment by JimLiu** [comment]
Could you send a PR for that?

**Comment by CaptainChemist** [comment]
I think I might have stumbled upon this as well. When I assign ref and try to look at the player's getState(), it says it is undefined. What's the best way to do this now?

**Comment by TSMMark** [comment]
This is a problem trying to use this package with React StrictMode.


### This way of assigning refs is outdated:

```jsx
<Player ref='player' />
```

Used like:

```js
this.refs.player.subscribeToStateChange(...)
```

### Now we should be doing this:

```jsx
<Player ref={(player) => { this.player = player }} />
```

I believe this `this.player` is now a reference to the DOM element itself, so this would not work:

```js
this.player.subscribeToStateChange(...)
```

But I could be wrong

**Comment by vivekd005** [comment]
I'm using the package in **React Strict Mode** and using ref like this
`<Player ref={(player) => { this.player = player }} />`
shows **undefined** when I try to console log. Is there any solution for this?

**Comment by vivekd005** [comment]
Did we find a way to use **ref** as I'm using this Pacakge in **React Strict Mode** and when I try to console log it shows **undefined**

I'm using it like this
`<Player ref={(player) => { this.player = player }} />`
