### ISSUE TITLE
Support for multiple instances on the same page?

### ISSUE THREAD

**Issue by joshuairl** [video-react/video-react#121]
Was just curious how it works with multiple instances of the player.

**Comment by JimLiu** [comment]
because there is no global variable 🤷‍♂️

**Comment by joshuairl** [comment]
Nah, I think what it needs is a way to key the instance, either automatically generated or manually via a prop.  So that Redux can be keyed and manage the instances separately.
So theoretically we can stop / start all players at once, etc.

Honestly, my needs are possibly just extreme but I'm building a video player that has a companion "advertisement" player that bounces off of the content video player.  It basically requires the state of the two players to work in tandem to ensure they don't play over each other.
