### ISSUE TITLE
do not support the video type of m3u8?

### ISSUE THREAD

**Issue by lamps0331** [video-react/video-react#129]
### Issue description

- version `#x.x.x`
- browser: `name-version`

### Steps to reproduce

1. step1
2. step2
3. step3

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Demo
You can fork from this template and add your code
https://codesandbox.io/s/2v95wlpvjj

**Comment by JimLiu** [comment]
https://video-react.js.org/customize/customize-source/
