### ISSUE TITLE
Customize ControlBar with "bookmarks"

### ISSUE THREAD

**Issue by MDrooker** [video-react/video-react#132]
Is there a way to create "bookmarks" on the ControlBar to quickly see points of interest in the video?

**Comment by JimLiu** [comment]
Sorry there is no bookmarks component.
This is the document on how to add your own component

**Comment by mondaychen** [comment]
@musaleAbhijeet please refer to https://video-react.js.org/customize/customize-component/

You can build your own component and make it a child of `ControlBar`. When user clicks it, you can call `seek` on the player to move to a different location of the video.
