### ISSUE TITLE
Video stops after a few seconds; video not fully loaded

### ISSUE THREAD

**Issue by kheyse-oqton** [video-react/video-react#133]
### Issue description

- version `0.11.2`
- browser: `chrome`

### Steps to reproduce issue
Use latest create-react-app (1.5.2) with react (16.4.1)
Add simple player
```
        <Player
          ref={ref => {this.player = ref}}
          src="https://media.w3.org/2010/05/bunny/trailer.mp4"
          autoPlay
          fluid>
          <ControlBar autoHide={false} />
        </Player>
```

### Actual behaviour
Video plays for a few seconds and then stops.
It seems only a few seconds of the video are loaded (confirmed in the network tab of the debugger)

I notice that the state of the player also contains an error:
MediaError {code: 3, message: "PIPELINE_ERROR_DECODE: video decode error"}

Is it possible the latest version of react is not supported yet?

**Comment by kheyse-oqton** [comment]
Seems to be the video source that had a problem when decoding in chrome (https://media.w3.org/2010/05/bunny/trailer.mp4 does not work when I browse to it). Had not considered that since it is one of the example videos on the website.
It does decode without problem on firefox.

**Comment by souravlahoti** [comment]
@kheyse-oqton   what is the solution? For me, the player stops downloading the chunks and pauses it but on refresh, it starts again from where it left for a few seconds and then stops again.

**Comment by kheyse-oqton** [comment]
> @kheyse-oqton what is the solution? For me, the player stops downloading the chunks and pauses it but on refresh, it starts again from where it left for a few seconds and then stops again.

The solution was using a different browser or different video file.
