### ISSUE TITLE
Poster image should appear after the video is finished

### ISSUE THREAD

**Issue by haimyyy** [video-react/video-react#135]
At the end of the video, the video component shows black screen instead of the poster image.

- version `0.10.4`
- browser: Chrome

I think the poster image should appear after the video is finished because right now I just see the last frame of the video (empty black screen).

**Comment by JimLiu** [comment]
it's hard to see that's a bug

**Comment by haimyyy** [comment]
Can you advice for workaround?

**Comment by JimLiu** [comment]
@haimyyy 
Handle the `onEnded` event by your self
https://github.com/video-react/video-react/blob/master/src/components/Video.js#L318-L320
