### ISSUE TITLE
PlaybackRate Issue - Negative rate has no effect

### ISSUE THREAD

**Issue by paolavness** [video-react/video-react#14]
Hi there, have encountered three issues with the playback rate - will create separate issues for each. let me know if this is preferred or if in future you would prefer them bundled in one ticket.

And thanks again for your ongoing work on this. My team is going forward with video-react because its such a high quality rollout, your responsiveness to issues is awesome and your focused on the main features - making video run awesomely!

### Issue: The PlaybackRate in the below code, the negative values have no effect. (tho the positive values do). Perhaps I am doing something wrong?

- version `#0.6.4`
- browser: Latest `chrome, firefox`

### Steps to reproduce issue
```
                <Player 
                  ref="player" 
                  muted={this.props.playerState.muted} 
                  autoPlay={this.props.playerState.autoPlay} 
                  startTime={this.props.playerState.startTime} 
                  videoWidth="634"
                  videoHeight="356" >
                    <BigPlayButton position="center" />
                    <source src={this.props.playerState.videoURL} />
                    <LoadingSpinner /> 
                    <ControlBar autoHide={false} >
                        <ReplayControl seconds={10} order={1.1} />
                        <ForwardControl seconds={10} order={1.2} />
                        <CurrentTimeDisplay order={4.1} />
                        <TimeDivider order={4.2} />
                        <PlaybackRate
                          rates={[-2, -1, 1, 1.25, 1.5, 2]}
                          order={7.1}
                        />
                        <VolumeMenuButton vertical={true}  />                 
                    </ControlBar>
                    <Shortcut shortcuts={this.newShortcuts} />
                  </Player>
```

### Steps to reproduce

1. Use the above code to create player instance
2. Select -ve rate - nothing changes.
3. Select a higher playback rate - rate increases
4. Select -ve rate - nothing change.
5. Select 1.00 rate - rate changes

### Expected behaviour
When negative rate is selected, rate slows down.

### Actual behaviour
When negative rate is selected, nothing happens

Thank you!
Paola

**Comment by JimLiu** [comment]
Thanks for your report!
Separate issues are easy to track.

If you want to slow down the rate, the playbackRate should be a value lower than 1.0 like 0.25 and 0.5.
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/playbackRate

But it can be a negative value, I'll check it.

**Comment by paolavness** [comment]
Aha! Works well with 0.xx values - 0.5, 0.25. This solutions works fine for me.
Coolio :)
