### ISSUE TITLE
change the delay to set user-active user-inactive classes

### ISSUE THREAD

**Issue by xxronis** [video-react/video-react#146]
Hi, this is more of a question.
Is there a way to change the delay of the user-activity classes switching?

Is this bit controlling it in Player.js?
```
    this.controlsHideTimer = setTimeout(() => {
      this.actions.userActivate(false);
    }, 3000);
```

A prop controlling this interval would be nice, thanks

**Comment by JimLiu** [comment]
Good suggestion, will add a property for it in next version

**Comment by mondaychen** [comment]
Any suggestion for a good name for this new prop? Maybe `deactivateTime`?

**Comment by mondaychen** [comment]
how about `userActivityTimeout` or `controlBarActiveTime`?

cc @xiaoyuhen

**Comment by xiaoyuhen** [comment]
I voted for ```controlBarActiveTime```
