### ISSUE TITLE
Module not found: Error: Can't resolve '~video-react/dist/video-react.css' in 'D:\react\

### ISSUE THREAD

**Issue by LastStranger** [video-react/video-react#150]
### Issue description
like the title said
- version `#x.x.x`
- browser: `name-version`

### Steps to reproduce

1. step1
2. step2
3. step3

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Demo
You can fork from this template and add your code
https://codesandbox.io/s/2v95wlpvjj

**Comment by LastStranger** [comment]
I already installed video-react in my PC, I can even do the "import { Player } from 'video-react';" but when I import "~video-react/dist/video-react.css"; it throws the error "Module not found", do I also need to install the video-react/dist/video-react.css?

**Comment by TonyGGC** [comment]
if you download to local,   you should import "file path/video-react.css";

if you do the “npm install ” ,   do like this: import "video-react/dist/video-react.css";

**Comment by mondaychen** [comment]
Hey @LastStranger hope the previous comments helped. 

I'm closing this since it's a general webpack/babel config question.
