### ISSUE TITLE
any method to cancel subscribeToStateChange

### ISSUE THREAD

**Issue by alanhg** [video-react/video-react#152]
like unsubscribeToStateChange.

I found mouse hover and leave can trigger change event when video is ended!

**Comment by JimLiu** [comment]
```
const unsubscribe = xxx.subscribeToOperationStateChange(handleChange)
unsubscribe()
```

**Comment by prashantham** [comment]
Can subscribeToOperationStateChange be called from player ref?

TypeError: element.subscribeToOperationStateChange is not a function

setPlayerRef = (element:any) => {
        this.unsubscribe = element.subscribeToOperationStateChange(this.onPlayeStateChange.bind(this));
        //this.element.subscribeToStateChange(this.onPlayeStateChange.bind(this));
    }

**Comment by JimLiu** [comment]
Try to get the `manager` instance from props
```js
const unsubscribe = this.props.manager. subscribeToOperationStateChange(handleChange)
unsubscribe()
```

**Comment by oseisaac** [comment]
I tried subscribeToStateChange but keep getting `TypeError: playerRef.subscribeToStateChange is not a function`
not sure what im doing wrong since I am using functional components.

here is the useEffect hook - trying to subscribe and set state at the same time
```
    React.useEffect(() => {
        playerRef.subscribeToStateChange(setstate(player?.getState()))
    });

```
Does any one know how to solve  this

**Comment by oseisaac** [comment]
> I tried subscribeToStateChange but keep getting `TypeError: playerRef.subscribeToStateChange is not a function`
> not sure what im doing wrong since I am using functional components.
> 
> here is the useEffect hook - trying to subscribe and set state at the same time
> 
> ```
>     React.useEffect(() => {
>         playerRef.subscribeToStateChange(setstate(player?.getState()))
>     });
> ```
> 
> Does any one know how to solve this

-----------SOLUTION --------------------

    React.useEffect(() => {
        if (player) {
            player.subscribeToStateChange(handleBind)
        }
    });

    function handleBind(state) {
        setstate(state);
    }
