### ISSUE TITLE
[BUG] the video has flicker on safari (hls source)

### ISSUE THREAD

**Issue by NuttaponTamburanavit** [video-react/video-react#153]
### Issue description

- version `#0.9.4`
- browser: `safari-11.1.2`

### Steps to reproduce

1. move to safari browser.
2. first load the video and click play.
3. the video has flicker.

### Expected behaviour
The video should not flicker like chrome browser.

### Actual behaviour
...

### Demo
Test on safari.
https://video-react.js.org/customize/customize-source/

**Comment by NuttaponTamburanavit** [comment]
You can check on this URL (safari) https://video-react.js.org/customize/customize-source/ 
and prepare with chrome browser. thanks for reply.

**Comment by JimLiu** [comment]
@NuttaponTamburanavit 
Sorry I have no idea with that, that looks like a hls.js issue:
https://video-dev.github.io/hls.js/demo/


My suggestion is that you might no need hls.js for safari, I remember Safari supports hls directly, or report an issue to hls.js.

**Comment by NuttaponTamburanavit** [comment]
Thank you. I will find next solutions to fix them.
