### ISSUE TITLE
重新给Player设定url

### ISSUE THREAD

**Issue by TonyGGC** [video-react/video-react#159]
### Issue description
在视频播放中， 给播放器赋一个新url的值， 怎么使播放器播放新发url
- version `#x.x.x`
- browser: `name-version`

### Steps to reproduce

1. step1
2. step2
3. step3

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Demo
You can fork from this template and add your code
https://codesandbox.io/s/2v95wlpvjj

**Comment by JimLiu** [comment]
Did you read the document?
