### ISSUE TITLE
PlaybackRate - CurrentTimeDisplay inconsistant counting

### ISSUE THREAD

**Issue by paolavness** [video-react/video-react#16]
### When playback rate is increase, the CurrentTimeDisplay counts inconsistently - speads up then slows down then speadsup, etc.

- version `#0.6.4`
- browser: Latest `chrome, firefox`

### Steps to reproduce issue
```
                <Player 
                  ref="player" 
                  muted={this.props.playerState.muted} 
                  autoPlay={this.props.playerState.autoPlay} 
                  startTime={this.props.playerState.startTime} 
                  videoWidth="634"
                  videoHeight="356" >
                    <BigPlayButton position="center" />
                    <source src={this.props.playerState.videoURL} />
                    <LoadingSpinner /> 
                    <ControlBar autoHide={false} >
                        <ReplayControl seconds={10} order={1.1} />
                        <ForwardControl seconds={10} order={1.2} />
                        <CurrentTimeDisplay order={4.1} />
                        <TimeDivider order={4.2} />
                        <PlaybackRate
                          rates={[-2, -1, 1, 1.25, 1.5, 2]}
                          order={7.1}
                        />
                        <VolumeMenuButton vertical={true}  />                 
                    </ControlBar>
                    <Shortcut shortcuts={this.newShortcuts} />
                  </Player>
```

### Steps to reproduce

1. Use the above code to create player instance
2. Select a higher playback rate and observe the CurrentTimeDisplay

### Expected behaviour
CurrentTimeDisplay should consistently count elapsed time - ie, increment in a consistent manner

### Actual behaviour
CurrentTimeDisplay is incrementing inconsistently 

Note: I have a listener on current time - perhaps this is impacting it. if you cannot reproduce your side, perhaps its my listener having a negative imapct.

**Comment by JimLiu** [comment]
Fixed in https://github.com/video-react/video-react/commit/85dfa66be523e8e1297eab25403b9032aa61896e
