### ISSUE TITLE
Add Replay Icon with no number in it 

### ISSUE THREAD

**Issue by importerror** [video-react/video-react#161]
### Currently, there are video icons for 5, 10 and 30 seconds. Icon for just replay without second is not there.  When the video completes would like to replay it again, something like youtube. 
<img width="248" alt="replay" src="https://user-images.githubusercontent.com/2376909/44457679-8331a300-a621-11e8-9360-bfc7401bd472.png">

- version `#x0.13.0`
- browser: `Any`

### Steps to reproduce

1. End of the video should display replay icon[optional].

### Expected behaviour
Should show a replay icon instead of play.

### Actual behaviour
It shows play button when the video ends.

**Comment by JimLiu** [comment]
You can add your own, this is an example on how to add it:
https://video-react.js.org/customize/customize-component/

**Comment by importerror** [comment]
Shall I send a PR for this feature?

**Comment by JimLiu** [comment]
@importerror 
> Shall I send a PR for this feature?

it would be great if you can send a PR for that, thanks!
