### ISSUE TITLE
BigPlayButton cannot show in ios-wechat?

### ISSUE THREAD

**Issue by AzyW** [video-react/video-react#165]
### Issue description

- version `video-react@0.13.0`
- browser: `ios-wechat`

### Steps to reproduce

after finist loading the page ,the big button cannot show in ios-wechat

### Demo
<Player
                    playsInline
                    src="https://media.w3.org/2010/05/sintel/trailer_hd.mp4">
 </Player>

**Comment by AzyW** [comment]
<Player
                    playsInline
                    src="https://media.w3.org/2010/05/sintel/trailer_hd.mp4">
                </Player>

**Comment by JimLiu** [comment]
Sorry I have no idea with that

**Comment by dxjdqc** [comment]
` <Player
      preload
      poster={props.videoImageUrl}
      src={props.videoUrl}
      height={240} width={'auto'}
    >
      <BigPlayButton position="center" />
      <Shortcut clickable={false} />
    </Player>`

BigPlayButton cannot show in ios-wechat

**Comment by xiaoyuhen** [comment]
Sorry, there is no plan to support the wechat browser.

**Comment by mouyong** [comment]
what is your ios version?

**Comment by sathishstar** [comment]
The same issue when I was using webview in react native app, me video in website & website link is used in the webview.

BigPlayButton is not re-rendered after the component player updates with 

> player.currentSrc

**Comment by mondaychen** [comment]
I did notice `player.currentSrc` being `null` in some random scenarios... My current assumption is that it's a browser "bug" to some extent:  it failed to set `currentSrc` for `<video>` element in time. I'll investigate later and maybe will submit a fix that takes care of all the problems caused by it.
