### ISSUE TITLE
how to change the default playbackRate?

### ISSUE THREAD

**Issue by FrankBATMAN** [video-react/video-react#166]
### Issue description

- version `0.13.0`
- browser: `chrome-69.0.3497.100`

### Steps to reproduce issue
```
componentDidMout() {
    this.refs.player.playbackRate = defaultPlaybackRate
}

render() {
    return (
        <Player ref="player">
            <source src={src} />
            <ControlBar>
                <PlaybackRateMenuButton rates={[5, 2, 1, 0.5, 0.1]} />
            </ControlBar>
        </Player>
    )
}
```
### Actual behaviour
defaultPlaybackRate may be one of the rates. 
for example, `defaultPlackbackRate = 5`,the code makes it's playing speed is 5.
but when i click Controlbar's PlaybackRateMenuButton , it's up options mean that we choose the 1.0 speed. in fact, player plays at speed 5.

i know it is because the function componentDidMout() calls after render(). 

so how can i solve it?

### Expected behaviour
defaultPlackRate is 5, player plays at speed 5 in the begining, **Also the choosed option in up options is the defaultPlackRate speed option**

**Comment by JimLiu** [comment]
That's a bug, will fix it
