### ISSUE TITLE
Can not play this video

### ISSUE THREAD

**Issue by yc850k** [video-react/video-react#17]
### Issue description

- version `#0.6.3`
- browser: `chrome-56.0.2924.87`

http://mov.bn.netease.com/open-movie/nos/flv/2014/09/10/SA4S7OINO_sd.flv

**Comment by JimLiu** [comment]
`Video-React` is a html5 player, so it only can play the video format which html5 video supports by default.

There is [a sample](https://video-react.github.io/customize/customize-source/) on how to customize your own source like HLS, for `.flv`, you can use [flv.js](https://github.com/Bilibili/flv.js), it works as the same way as [hls.js](https://github.com/dailymotion/hls.js).

Another choice is [video.js](https://github.com/videojs/video.js)

**Comment by yc850k** [comment]
Thanks!
