### ISSUE TITLE
I cannot add text tracks

### ISSUE THREAD

**Issue by jerlam06** [video-react/video-react#171]
I am trying to add text tracks with addTextTrack():

````
componentDidMount() {
		this.refs.player.addTextTrack("./myTrack.vtt")
	}

	render() {
		return (
			<div className="App">
				<div className="video-container">
					<Player ref="player">
						<HLSSource
							isVideoChild
							src="https://abc/asdwd45qwed45/playlist.m3u8?q=360"
							autoPlay={true}
						/>
					</Player>
				</div>
			</div>
		);
	}
````

But here is the error I get:

> TypeError: Failed to execute 'addTextTrack' on 'HTMLMediaElement': The provided value './myTrack.vtt' is not a valid enum value of type TextTrackKind.

**Comment by rosemarystanley** [comment]
Looking at the source code, it looks like you need to add arguments to the method... ex: 

```
this.player.addTextTrack({
        src: './myTrack.vtt',
        kind: 'subtitles',
        srclang: 'en',
        label: 'English'
      })
```
I haven't had a chance to test it yet myself but I'll need to soon.

**Comment by mondaychen** [comment]
`player.addTextTrack` is simply passing the arguments to call `addTextTrack` on the video element. I would recommend using `<track>` to avoid browser compatibility problem.

If you have to use `addTextTrack`, the first argument should be one of the 5 enum literals. See http://html5index.org/Media%20-%20TextTrackKind.html

**Comment by mondaychen** [comment]
I'm closing this since it's not really a problem of video-react
