### ISSUE TITLE
Retrieve current frame?

### ISSUE THREAD

**Issue by cinjon** [video-react/video-react#173]
Similar to #172 , this is not a bug but I am looking for a way to retrieve the current frame as a data object that I can then pass up to a server. Is that available?

Thanks!

**Comment by mondaychen** [comment]
Hi. Thanks for using this project. 

I'm not aware of any technique that can retrieve image object from a video player on browser side. Even if there's such a way, I don't think it should be part of this project. A plugin should be better.
