### ISSUE TITLE
不能自动播放？设置autoplay也是不可以的

### ISSUE THREAD

**Issue by li941168803** [video-react/video-react#174]
### Issue description

- version `#x.x.x`
- browser: `name-version`

### Steps to reproduce

1. step1
2. step2
3. step3

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Demo
You can fork from this template and add your code
https://codesandbox.io/s/2v95wlpvjj

**Comment by mondaychen** [comment]
Please use English and provide more details when creating issues
