### ISSUE TITLE
weixin:TypeError: Object.assign is not a function

### ISSUE THREAD

**Issue by zzj0222** [video-react/video-react#179]
### Issue description

- version `#x.x.x`
- browser: `name-version`

### Steps to reproduce

1. step1
2. step2
3. step3

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Demo
You can fork from this template and add your code
https://codesandbox.io/s/2v95wlpvjj

**Comment by JimLiu** [comment]
You need to add you own polyfill of `Object.assign` for Weixin
