### ISSUE TITLE
Support fullscreen on iphone6s

### ISSUE THREAD

**Issue by yc850k** [video-react/video-react#18]
### Issue description

- version `#0.6.4`
- browser: `safari on ios 10.2.1`

### Steps to reproduce

1. set <Player playsInline>
2. click <BigPlayButton>
3. click fullscreen button in <ControlBar>

### Expected behaviour
native full-screen in browser.

### Actual behaviour
video height is 0

It needs some code like this:
```javascript
const videoElm = document.getElementsByTagName("video")[0];
if (videoElm.webkitSupportsFullscreen) {
  if (videoElm.webkitDisplayingFullscreen){
    videoElm.webkitExitFullscreen();
  } else {
    videoElm.webkitEnterFullscreen();
  }
}
```

https://developer.apple.com/library/content/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/ControllingMediaWithJavaScript/ControllingMediaWithJavaScript.html
https://developer.apple.com/reference/webkitjs/htmlvideoelement

**Comment by JimLiu** [comment]
Did you try to add `playsInline` property for `Player` component? 
Check the document: https://video-react.github.io/components/player/

**Comment by yc850k** [comment]
I did indeed.
```javascript
function Video({ loading, poster, url }) {
  function renderPlayer() {
    return (
      <Player
        poster={poster}
        playsInline
        preload="auto"
      >
        <source src={url} />
        <BigPlayButton position="center" />
        <LoadingSpinner />
        <ControlBar>
          <VolumeMenuButton disabled />
        </ControlBar>
      </Player>
    );
  }
```
