### ISSUE TITLE
Native HLS source in safari (macOS and iOS) doesn't stop xhr request after component unmounted

### ISSUE THREAD

**Issue by FarzadKarkhani** [video-react/video-react#183]
### Issue description

- version `#0.11.2`
- browser: `Safari Version 12.0 (14606.1.36.1.9) macOS` `Safari iOS 12.1`

### Steps to reproduce

1. step1
I copy pasted this class
```js
import React from 'react';
import { Player } from 'video-react';

export default (props) => {
  return (
    <Player
      autoPlay
      src="http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8"
    >
    </Player>
  );
};
```
2. step2
`npm start`

3. step3
After start playing, go to another internal url without refresh (video-react on mounted).

### Expected behaviour
When I look Network tab in Inspect Element, request for .ts file must be stop.

### Actual behaviour
It's still request for .ts files and it never stop until refreshing the page.

**Comment by mondaychen** [comment]
I'm not sure if I fully understand it. By `go to another internal url without refresh` do you mean you type something else in browser url bar? If so, this is handled by the browser, not this component.

Leave another comment if I got you wrong.
