### ISSUE TITLE
Fullscreen Not working properly on any browser in Windows 10

### ISSUE THREAD

**Issue by tworkman512** [video-react/video-react#185]
### Issue description

- version `release-0.13.1`
- browser: `all current browser versions in Windows 10`

### Steps to reproduce

1. Visit https://video-react.js.org/ on a Windows 10 machine using any current version browser (e.g. Chrome)
2. Navigate to the Basic Example video  
3. Click the button in the control bar to expand the video to fullscreen 

### Expected behavior
User should see the fullscreen version of the video along with the control bar. 

### Actual behavior
What happens instead, is the user only sees the top portion of the fullscreen video and the control bar is not displayed at all. The only way to exit from the video is to hit the ESC key, which is a poor user experience.

**Comment by gaoqiang19514** [comment]
![image](https://user-images.githubusercontent.com/13738577/50939329-4d4d6800-14b7-11e9-9009-be69d4ce3876.png)

**Comment by gaoqiang19514** [comment]
My system is win10, it can be full screen

**Comment by gaoqiang19514** [comment]
> @video-react/core hi team, any of you have a windows 10 machine?

My system is win10 and Fullscreen works properly
