### ISSUE TITLE
Control Bar className="my-class" propagates to children

### ISSUE THREAD

**Issue by mrk197702** [video-react/video-react#186]
Hello 
I'm trying to customize the controll bar.  I added as said in the examples:
`<ControlBar autoHide={false} className="my-class" />`

The issue is that "my-class" propagates also to ControlBar's children like ProgressControl, PlayToggle ect, and that's unwanted. How can I avoid this problem?

Thanx

**Comment by tangentlin** [comment]
Sorry for hijacking this issue, I tried to create a new issue and after I have filled in all the fields, I notice the "Submit an Issue" button remains disabled.

**Comment by nicu-chiciuc** [comment]
I think this happens because the props passed to ControlBar are passed like this to its children:
```
<PlayToggle
        {...this.props}
        key="play-toggle"
        order={1}
      />
```
https://github.com/video-react/video-react/blob/master/src/components/control-bar/ControlBar.js#L44

**Comment by cronin4392** [comment]
@nicu-chiciuc I dug into this a bit, thinking it would be a easy fix and realized it goes deeper than I thought. I attempted to pull out `className` from the props in `getDefaultChildren` like so:

```
const { className, ...rest } = this.props;
<PlayToggle
    {...rest}
    key="play-toggle"
    order={1}
    />
```

This did not work. I figured out that the prop passing is happening at a much deeper / engrained level. `mergeAndSortChildren` is doing some magic where it merges `parentProps`, `defaultProps`, and `element.props`. https://github.com/video-react/video-react/blob/master/src/utils/index.js#L89

Now I am no longer sure the best place to extract `className` from.

**Comment by mondaychen** [comment]
@cronin4392 I think you are right. `mergeAndSortChildren` did this.

Actually not only `ControlBar`, but the same thing happens everywhere. If you put `className` on `Player`, it will be propagated onto all its children, unless overwritten by another `className`.

For now, to avoid this behavior, you need to specify all 7 possible children of `<ControlBar>` and put `className=""` in all of them, like this:

```
<ControlBar autoHide={false}>
  <PlayToggle className="" />
  <VolumeMenuButton className="" />
  ... 
</ControlBar>
```

I think this is unwanted behavior, if not a bug. A `className` prop should only affect the dom of the current component. @JimLiu do you agree?
