### ISSUE TITLE
Display of loading bar during autoPlay

### ISSUE THREAD

**Issue by Rocket-Bang** [video-react/video-react#188]
If you have a large video during the second video consecutive playback after the first video, you probably need a loading bar.
Is there a solution?

### Continuous playback is using the following source code.
-> this.refs.player.subscribeToStateChange (this.handleStateChange.bind (this));

**Comment by mondaychen** [comment]
Hi. If you can provide a full demo, I'll be able to help you better. But in general, I think you can check the `state` in `handleStateChange`, whenever you find the video source is different (meaning it's a second video), you can update a local state to display something.
