### ISSUE TITLE
Unknown prop `playsInline` on <video> tag

### ISSUE THREAD

**Issue by filipdanic** [video-react/video-react#20]
### Issue description

- version `0.6.4` (latest) 
- browser: `Chrome, version 56.0.2924.87 (64-bit)`

### Steps to reproduce issue

Added this to my code:

```
<Player 
    src={video.url} 
    poster={video.thumbnail} 
/>
```

This works as expected and the video player is rendered and working. However, there is an error in the console:

```
Warning: Unknown prop `playsInline` on <video> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in video (created by Video)
    in Video (created by Player)
    in div (created by Player)
    in Player (created by ViewPatientsPage)
```

Generally, this something that only bugs you in development mode. None the less, it would be ideal for the `playsInline` prop not to be applied directly to the video unless the client browser is Safari.

**Comment by JimLiu** [comment]
There is no this warning if you upgrade you react-dom to a newer version.
But it should not add this property if the user does not add `playsInline` property.
Will fix it in next version.

**Comment by JimLiu** [comment]
Since the upgrade of `react-dom` can solve this problem, so I do not intend to change this part.
