### ISSUE TITLE
When video play in safari browser on full screen mode ,it only shows poster image

### ISSUE THREAD

**Issue by shweta2345** [video-react/video-react#201]
### Issue description

- version `#x.x.x`
- browser: `name-version`

### Steps to reproduce

1. step1
2. step2
3. step3

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Demo
You can fork from this template and add your code
https://codesandbox.io/s/2v95wlpvjj

**Comment by mondaychen** [comment]
Hi. I'm not able to reproduce this issue. I tried our post image demo https://video-react.js.org/components/poster-image/ using Safari on both macOS and iOS, both of them worked perfectly.
