### ISSUE TITLE
Video is not playing on any mobile devices

### ISSUE THREAD

**Issue by ruige92** [video-react/video-react#202]
### Issue description
I'm using this plugin in my react app, when browsing on web browsers everything seems to be working fine, i.e. the video plays as expected.

However, I tried to play videos on mobile, tablet devices and the only thing that is showing is the loading circle...

- version `#0.13.2`
- browser: `iphone safari, iphone google chrome`

### Steps to reproduce

1. Open the browser up on your phone, go to http://lol.borui.co.uk/champions/Aatrox
2. Click any of his abilities icon, he should have 5, the ones labelled with Q, W, E and R

### Expected behaviour
Video should play automatically

### Actual behaviour
Video never seem to load or play. All there is is a loading circle, loop forever.

**Comment by xiaoyuhen** [comment]
hi @ruige92 

This is not a ```video-react``` bug. This bug occurs because of WebM video format does not appear to be currently supported by Safari.

**Comment by xiaoyuhen** [comment]
> Chrome for iOS has some pretty major technical restrictions imposed by the App Store, such as the requirement to use the built-in UIWebView for rendering, no V8

so basically, Chrome for iOS compatibility is consistent with safari.

**Comment by ruige92** [comment]
@xiaoyuhen I guess the only workaround is to use a more compatible video format in this case, thanks for the information!
