### ISSUE TITLE
Confusing implementation of mouseover on ProgressBar

### ISSUE THREAD

**Issue by don-p** [video-react/video-react#209]
### Issue description

- version `#0.13.2`
- browser: all

### Steps to reproduce

1. Load video into player.
2. Play video briefly, then pause.
3. Mouse over seek bar to a location where video has not preloaded.
4. Click in seek bar at this location to seek video.
5. Video will seek to location, but in some scenarios the slider will not update until the mouse is moved off of the progress control.

- or -

1. Load video into player.
2. Play video briefly, then pause.
3. Drag or click in seek bar so that slider is near end of video.
4. Load new video source into existing player.
5. Note that slider shows same position at end, although new video is loaded and seek position is actually at beginning.
6. Mouse over progress control, and slider jumps to 0:00.

### Expected behaviour
Slider position should update on mouseUp when clicked, not on mouseLeave of ProgressControl.
Slider position should reset when new video source is loaded.

### Actual behaviour
See repro steps.

**Comment by xiaoyuhen** [comment]
hi,@don-p 
I didn't reproduce this issue in our demo. Can you provide more information for us to investigate?
