### ISSUE TITLE
does this work with youtube and vimeo videos url? (question)

### ISSUE THREAD

**Issue by jasan-s** [video-react/video-react#21]

**Comment by JimLiu** [comment]
No!
Youtube and Vimeo videos use iFrame to play video.

Video-react is only for Html5 videos.

**Comment by subodhk01** [comment]
@JimLiu Do you know any better library that supports youtube?

**Comment by uche-okoroafor** [comment]
> @JimLiu Do you know any better library that supports youtube?

Yes ReactPlayer,it supports both HTML and iframe players [https://www.npmjs.com/package/react-player](url)
