### ISSUE TITLE
Broken style link

### ISSUE THREAD

**Issue by ayshiff** [video-react/video-react#219]
### Issue description
_This is a documentation issue_

It seems like there is a **broken link import** on the README.
Which leads to a **404 error**.

![capture d ecran 2019-02-04 a 17 58 54](https://user-images.githubusercontent.com/32459935/52223735-91f5d480-28a6-11e9-9103-c15dafa734fe.jpg)

**Comment by xiaoyuhen** [comment]
@ayshiff 
Thank you very much for reporting on this bug.

It has been fixed and can be used normally now.

Maybe providing a css file reference via ```github.io``` is not a good way, we will consider providing a CDN address
