### ISSUE TITLE
Warning: Failed prop type: Invalid prop `width` of type `string` supplied to `Player`, expected `number`

### ISSUE THREAD

**Issue by RaduGabor** [video-react/video-react#220]
### Issue description

- version `#0.13.2`
- browser: `Chrome`

### Steps to reproduce issue

`<Player width="auto" />`
 
### Steps to reproduce

Add Player component with width "auto" prop.

### Expected behaviour

There should be no warning in console

### Actual behaviour

There is an error log in console:

```
Warning: Failed prop type: Invalid prop `width` of type `string` supplied to `Player`, expected `number`.
    in Player (at VideoPlayer.jsx:21)
```

### Demo

You can fork from this template and add your code
https://codesandbox.io/s/x277qol4rz

**Comment by xiaoyuhen** [comment]
@RaduGabor 

Very weird, I didn't find this bug locally, but the demo you provided does have this problem. 

I will try to fix this problem this week.

**Comment by mondaychen** [comment]
The demo you provided is using video-react version 0.11 instead of the latest 0.13. That's why it happened.

I guess it's time to update our base demo. Thanks for reporting :)
