### ISSUE TITLE
Question : How to move seekbar location

### ISSUE THREAD

**Issue by PierreSachot** [video-react/video-react#223]
### Issue description

Hi, I would like to say that your package is cool and really easy to use. I'm new in web development world, so I'm sorry if my question seems pretty easy.  I would like to know if it is possible to move the seekbar from it's default location. I changed some properties in your CSS and it works, but the problem is that my new location doesn't match expected js position. This means that I can't click on the new seekbar position.

Thanks a lot for your help.

**Comment by xiaoyuhen** [comment]
hi @PierreSachot 

Did you mean that you want to customize the location of the ```seekbar```?

Will have some difficulties, This project is heavily inspired by video.js, and most of our CSS styles came from video.js's styles. so, Basically, we don't want you to change its style.

I suggest you write a ```control-bar``` component yourself.

**Comment by PierreSachot** [comment]
Hier @xiaoyuhen, 
Yeah that's exactly what I was thinking to. So, can I overrite videojs's CSS is it absolutely forbidden ? And Can I use videojs Api or is it impossible ? 

Thanks a lot for the Quick response! I will watch to create my own control bar

**Comment by xiaoyuhen** [comment]
@PierreSachot 

you can use videojs style for your own control bar. just dont modify ```video-react``` seekbar style.
