### ISSUE TITLE
Not reloading when changing url with state

### ISSUE THREAD

**Issue by mahdidavoodi7** [video-react/video-react#224]
Hi,
Im giving url to the Player from state but i want when i change the state , the Player do not reload itself and just play the video from the new url.
- I did this for securing my video 
- The url changes every 30 seconds
- the video is same just url has changed

Here is my code : 
```javascript
class Lesson extends React.Component {
  state = {
    time: 0,
  }
  generateSecret = (time) => {
    //some code for generating secret 
  }
  componentDidMount() {
    this.interval = setInterval(() => {
      this.setState({time: new Date().getTime()});
    }, 10000);
  }
  render(){
    return( 
      <Player src={'http://localhost:8585/video/' + this.generateSecret(this.state.time)}>
        <BigPlayButton position="center" />
      </Player>
    )
  }
}
```
Any help regarding this would be helpful

**Comment by xiaoyuhen** [comment]
Changing src will definitely reload, can't give you any help, because it is impossible to achieve.


But if your video is in fmp4 format, you can try MSE for ```byte-range``` loading.

**Comment by mahdidavoodi7** [comment]
What is your opinion for securing my video

**Comment by mahdidavoodi7** [comment]
@xiaoyuhen 
Does video-react support FMP4 format ? and have MSE ??

**Comment by xiaoyuhen** [comment]
@mahdidavoodi7 

```video-react``` support FMP4 format, but ```video-react``` don't use MSE. very sorry about that.

**Comment by mahdidavoodi7** [comment]
@xiaoyuhen 

How about HLS ? Does `video-react` support it ??

**Comment by xiaoyuhen** [comment]
```video-react``` use hlsjs, so yeah, `video-react` support it

**Comment by mondaychen** [comment]
Any further comments/concerns? If not I'm closing this issue
