### ISSUE TITLE
Mixed Content

### ISSUE THREAD

**Issue by realitybreakdown** [video-react/video-react#225]
Getting this error on dev tools in Google Chrome:

> Mixed Content: The page at (my site) was loaded over HTTPS, but requested an insecure stylesheet 'http://video-react.js.org/assets/video-react.css'. This request has been blocked; the content must be served over HTTPS.

Any suggestions?

**Comment by xiaoyuhen** [comment]
hi @realitybreakdown 

If you use HTTPS on your website, please use ```https://video-react.js.org/assets/video-react.css``` adress

**Comment by realitybreakdown** [comment]
Hi @xiaoyuhen 

I have tried this but am still getting the error.
