### ISSUE TITLE
LoadSpinner not visible even when the movie is still buffering

### ISSUE THREAD

**Issue by shirlyf** [video-react/video-react#228]
**Describe the bug**
When testing with fast 3G and playing the movie for the first time, the LoadingSpinner isn't being displayed when the video is still buffering and black screen is shown.

**To Reproduce**
1. Change connection speed to fast 3G in chrome developer tool(network tab)
2. Play the movie for the first time (or clean cache and hard reload)
3. Wait for LoadingSpinner to display and see when it disappear..

**Expected behavior**
The LoadingSpinner is visible till the movie starts playing.

**Desktop (please complete the following information):**
 - Windows 10
 - Browser: Google Chrome (72.0.3626)

Cheers,
ShirlyF

**Comment by mondaychen** [comment]
When the video is buffering, I did notice a gap between when the loading spinner is gone and the video actually starts to play. Will investigate. Thanks for reporting!

**Comment by shirlyf** [comment]
Hi mondaychen, Thanks for making the effort to fix this. do you have any estimation when it will be fixed?

**Comment by mondaychen** [comment]
Hi @shirlyf I've been busy running some family errands these days. I'll start to work on it next week and hopefully get it done as soon as possible. If you have any clue that might help my investigation, please let me know. Thanks!

**Comment by shirlyf** [comment]
Hi,
Thanks for the fix.
when this will be available for me?
 
- Shirly

**Comment by mondaychen** [comment]
Hi @shirlyf 

It should be available in the latest version. Please let me know if it fixes your problem. Thank you!

**Comment by shirlyf** [comment]
Yes it worked !
Thank you.
