### ISSUE TITLE
preload="auto" is not overwritable

### ISSUE THREAD

**Issue by rubeonline** [video-react/video-react#229]
**Describe the bug**
When I set preload="none" it is on auto.

```
    <Player
        playsInline
        preload="none"
    >
        <source src={video.file.url} type="video/mp4" />
        <BigPlayButton position="center" />
    </Player>
```

**Expected behavior**
preload should be set to none.

**Additional context**
Is this an usage error or a bug?

**Comment by mondaychen** [comment]
I can confirm this bug. It was introduced in a recent bug fix #192 which stopped passing props from `<Player>` to `<Video>`. Will submit a fix soon.

Thanks for reporting!
