### ISSUE TITLE
*feature question* Facebook-style video

### ISSUE THREAD

**Issue by savovs** [video-react/video-react#23]
How would you go about allowing only one video to play at the same time and autoplay when scrolled over? Basically the same way Facebook does it in their news feed.

**Comment by JimLiu** [comment]
You could control it by yourself. There are some methods to control the player, for example: 

- an array to store all the players
- a variable to store the current play
- find the currently visible player when scrolled over

API
https://video-react.js.org/components/player/

**Comment by savovs** [comment]
Thanks! I'll post something here once I give it a shot.
