### ISSUE TITLE
Untranspiled output was published to npm for version 0.13.3

### ISSUE THREAD

**Issue by skyuplam** [video-react/video-react#232]
**Describe the bug**
The package output in `lib/*` are basically the same as the one in `src/*`.

**To Reproduce**
Checkout the published package in npm and open the files in `lib` folder.

**Expected behavior**
A transpiled version of the source code that can be run without any transpiler.

**Screenshots**

**Desktop (please complete the following information):**
Any

**Additional context**

**Comment by mondaychen** [comment]
I think you will find what you are looking for in the dist folder

**Comment by skyuplam** [comment]
> I think you will find what you are looking for in the dist folder

Yes, it can be found in the `dist` folder but according to the [main field in package.json](https://github.com/video-react/video-react/issues/new/choose?permalink=https%3A%2F%2Fgithub.com%2Fvideo-react%2Fvideo-react%2Fblob%2Fddb9acd2b7f706f14c6630dacf625f08c41a1c0b%2Fpackage.json%23L5), the primary entry point is `lib/index.js`.

This mean it is no long doable to `require('video-react')` a simple node environment without a transpiler. It has to change to `require('video-react/dist/video-react')`. It becomes a breaking changes from `version 0.13.2` to `version 0.13.3` since the files under `lib` folder is well transpiled before `version 0.13.3`.

BTW, what's the point of having both `dist` and `lib` output folders?

**Comment by mondaychen** [comment]
@skyuplam to answer your question, `lib` is for "modern" JS environments which support ES modules. `dist` is for bundled "umd" version which directly works for browsers.

Before 0.13.3, we did have support for commonjs in `lib` too (which uses the `require` syntax you mentioned), but since video-react is most likely a browser only package, we removed the support when we were upgrading babel in #199.

Can you give me an example where you need to use this package in nodejs env or some other env that only support commonjs but not ES modules? If so I'm happy to add it back. 

Thank you!

**Comment by skyuplam** [comment]
@mondaychen Thanks for your promptly reply.

Regarding to the folder-ish/`package.json` filed, the `main` field in `package.json` usually refers to the module that can be `require('module-name')`, as stated from [npm doc](https://docs.npmjs.com/files/package.json#main) and there is [a proposal](https://github.com/dherman/defense-of-dot-js/blob/master/proposal.md#typical-usage) to allow the Javascript ecosystem to upgrade to ES2015 modules without breaking backwards compatibility by specifying a `module` key in the `package.json` file.

> Before 0.13.3, we did have support for commonjs in lib too (which uses the require syntax you mentioned), but since video-react is most likely a browser only package, we removed the support when we were upgrading babel in #199.

I think changing of module supporting is a breaking change and should not be simply increase the patch version number, i.e. from `v0.13.2` to `v0.13.3`, and it should be clearly stated in the changelog or in the release statement. It is not a bug fix.

> Can you give me an example where you need to use this package in nodejs env or some other env that only support commonjs but not ES modules? If so I'm happy to add it back.

Server side rendering.

Anyways, I would suggest:
+ Specify the `module` field in `package.json` for ES modules
+ Specify the `main` field in `package.json` for commonjs (if this package is going to continuously support commonjs.)
+ Apply a more significant versioning, say `v0.14.0` for dropping the support of commonjs, and state the breaking change in the change log / release note (if dropping commonjs support)

**Comment by mondaychen** [comment]
Makes sense. I'll submit a fix soon.

**Comment by mondaychen** [comment]
Please check if the latest version fixed your issue.

**Comment by jeremyckahn** [comment]
I believe that this PR is also necessary to fully fix this issue: video-react/video-react#242
