### ISSUE TITLE
Cannot read property 'subscribeToStateChange' of undefined

### ISSUE THREAD

**Issue by sehgalvibhor** [video-react/video-react#236]
I have two different video players paginated (different tabs on the same web page) , I can subscribeToStateChange on the first video player using `this.refs.player.subscribeToStateChange(this.handleStateChange.bind(this));` but If try to do the same for the other player (player2).  It gives me the following error `Cannot read property 'subscribeToStateChange' of undefined`. Somehow, it's not able to find player2, maybe because its in the other tab?

**Comment by mondaychen** [comment]
It might be the way you set your `refs`. Do you mind paste some code to show how it happens?

**Comment by sehgalvibhor** [comment]
Placing subscribeToStateChange in componentDidUpdate() fixed the issue.
Thanks!

**Comment by oseisaac** [comment]
I tried subscribeToStateChange but keep getting `TypeError: playerRef.subscribeToStateChange is not a function`
not sure what im doing wrong since I am using functional components.

here is the useEffect hook - trying to subscribe and set state at the same time
```
    React.useEffect(() => {
        playerRef.subscribeToStateChange(setstate(player?.getState()))
    });

```

**Comment by oseisaac** [comment]
> I tried subscribeToStateChange but keep getting `TypeError: playerRef.subscribeToStateChange is not a function`
> not sure what im doing wrong since I am using functional components.
> 
> here is the useEffect hook - trying to subscribe and set state at the same time
> 
> ```
>     React.useEffect(() => {
>         playerRef.subscribeToStateChange(setstate(player?.getState()))
>     });
> ```


-----------SOLUTION --------------------

    React.useEffect(() => {
        if (player) {
            player.subscribeToStateChange(handleBind)
        }
    });

    function handleBind(state) {
        setstate(state);
    }
