### ISSUE TITLE
The newest version, 'import' isn't bable into require.

### ISSUE THREAD

**Issue by MapleShaw** [video-react/video-react#237]
In the file /node_modules/video-react/lib/index.js, 'import' isn't bable into require

![image](https://user-images.githubusercontent.com/1726349/53937317-b207f600-40e7-11e9-99c8-4dc8371fb2e0.png)

**Comment by mondaychen** [comment]
duplicate with #232

will release a new version soon

**Comment by mondaychen** [comment]
Please check if the latest version fixed your issue.

**Comment by jeremyckahn** [comment]
The latest `0.13.4` release fixed the original issue for me (which I was experiencing) but created a different one. I don't have details I can share yet (all of my error messages reference internal IP at my company), but I will follow up on this issue once I have something specific to share.

**Comment by jeremyckahn** [comment]
More info: I think that video-react is publishing build artifacts that are incompatible with Webpack-based project toolchains. Based on my debugging, it appears that the `package.json`'s [`main`](https://github.com/video-react/video-react/blob/38a35c256199a90263001e1ca626c3f49d2a37a0/package.json#L5) needs to be `"dist/video-react.full.js"` and it should have `"module": "dist/video-react.es.js"`. This appears to be somewhat of a reversal of [this "Rollback to webpack" commit](https://github.com/jeremyckahn/video-react/commit/dfcfc2d9d677daecf4bc3f73595cf88505904d7a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2), but it fixes all of my issues. I hope that this will also maintain compatibility with Rollup-based projects, but I have never used Rollup so I don't know for sure.

I will prepare a PR for this and have it ready shortly!

**Comment by mondaychen** [comment]
Can you share your webpack-based project config file? Does it have no babel dependency?

**Comment by jeremyckahn** [comment]
As I mentioned in [my other comment](https://github.com/video-react/video-react/pull/242#issuecomment-472095070), I think I misunderstood and mis-explained my issue (sorry for the confusion!). The project I am using `video-react` in is a Lerna-based common component monorepo and actually does not use Webpack at all — it uses Babel directly. If it's helpful, here is my `babel.config.js`:

```js
/* global module:true */
'use strict';

module.exports = {
	presets: ['@babel/preset-react', '@babel/preset-env'],
	plugins: ['@babel/plugin-proposal-class-properties'],
};
```

**Comment by mondaychen** [comment]
@MapleShaw and @jeremyckahn can you check if 0.13.5 fixes this issue? Thanks

**Comment by jeremyckahn** [comment]
@mondaychen It's working perfectly for me. Thanks so much for the timely fix! 🙌

**Comment by mondaychen** [comment]
@jeremyckahn Thank you for your help on this!
