### ISSUE TITLE
点击留白处报错

### ISSUE THREAD

**Issue by dicklwm** [video-react/video-react#24]
### Issue description

- version `0.7.3`
- browser: `chrome 57.0.2987.110 (64-bit)`

### 我的代码

```
       //，循环item里面的视频，其中file是视频的URL路径
      <Player width={300} height={300} preload="none" ref={'player' + item.id} >
              <source src={item.file} />
              <BigPlayButton position="center"/>
              <LoadingSpinner />
              <ControlBar disableDefaultControls={true}>
                <PlayToggle />
                <VolumeMenuButton vertical={true}/>
                <DurationDisplay/>
                <ProgressControl/>
                <FullscreenToggle/>
              </ControlBar>
      </Player>
```

### 效果图
![image](https://cloud.githubusercontent.com/assets/19289258/24574936/cdba2162-16cc-11e7-8ee5-e37e28870ff1.png)

效果是完全正确的，但是我在暂停或者播放的时候，点击留白处，他报这个错了
```

player.js:59 Uncaught TypeError: Cannot read property 'play' of null
    at Manager.play (player.js:59)
    at Object.play (Manager.js:54)
    at Shortcut.togglePlay (Shortcut.js:239)
    at Shortcut.handleClick (Shortcut.js:312)
play @ player.js:59
(anonymous) @ Manager.js:54
togglePlay @ Shortcut.js:239
handleClick @ Shortcut.js:312

```

虽然报错了，但是不影响效果，我想问下我该怎么解决这个报错呢？

### 预期效果
不影响播放效果的同时，点击留白处不报错

**Comment by JimLiu** [comment]
我这里不能复现
你能不能用React开发工具看看Shortcut组件属性，正常的应该像这样：
![image](https://cloud.githubusercontent.com/assets/648674/24575114/0fb70630-1663-11e7-9bd2-ec272a4a717f.png)

**Comment by dicklwm** [comment]
![image](https://cloud.githubusercontent.com/assets/19289258/24577029/d9a869e4-16f8-11e7-811f-0486fbfbf2ea.png)

我的是这样的，好像是正常的，我这里是几个Player的，像微信的视频那样的

**Comment by JimLiu** [comment]
抱歉我还是无法复现
你可以考虑通过 https://jsfiddle.net/ 创建一个能复现的项目

**Comment by dicklwm** [comment]
我另开一个项目想去重现，但是发现这bug没有了，原来的项目的bug也没有了，我也没做update什么的，那就先这样吧，Close了
