### ISSUE TITLE
Remove keydown listener in Slider on unmount

### ISSUE THREAD

**Issue by mehdikazi** [video-react/video-react#240]
**Describe the bug**
Currently when the slider is focused it adds a document listener to detect arrow keys for scrubbing. However if you never remove focus from the slider and the component gets unmounted the listener will still be part of the document causing the arrow keys to throw errors.

**To Reproduce**
1. Go to: https://codesandbox.io/s/vnwnxq5vp0
2. Click play
3. Click on the slider
4. Use arrow keys to scrub video
5. Press escape
6. Open console
7. Focus on page
9. Use arrow keys and see errors appear in the console

**Expected behavior**
When the player is unmounted all document listeners should be removed.

**Desktop (please complete the following information):**
 - OS: Mac 
 - Browser: Chrome
 - Version: 72.0.3626.119

**Comment by mondaychen** [comment]
I was not able to reproduce it in the demo you provided

**Comment by mehdikazi** [comment]
Here's a recording of the repo steps using the demo provided. The main steps are:
1. Press play
2. Click on the slider to scrub the video forward
3. Press escape to make the player unmount
5. Use any arrow keys for the errors to come up in the console. 

![2019-03-13 19 46 55](https://user-images.githubusercontent.com/14842579/54327997-82fef200-45c9-11e9-8073-8f013039a55e.gif)

**Comment by mondaychen** [comment]
Ah, I missed the "click the slider" step. I'm able to reproduce now. Thanks for reporting!
