### ISSUE TITLE
Module not found: Error: Can't resolve '@babel/runtime/helpers/interopRequireWildcard' in '/opt/build/repo/node_modules/video-react/lib'

### ISSUE THREAD

**Issue by arturhaddad** [video-react/video-react#241]
**Describe the bug**
When I deploy my application on Netlify it gives me the following error:
`Module not found: Error: Can't resolve '@babel/runtime/helpers/interopRequireWildcard' in '/opt/build/repo/node_modules/video-react/lib'`

In my local environment it was working OK, until I tried to reproduce it updating video-react.
So i executed `npm install --save video-react` and now i can't even access my app in my local, this message appears:
```
Failed to compile.

./node_modules/video-react/lib/components/Player.js
Module not found: Can't resolve '@babel/runtime/helpers/assertThisInitialized' in '/Users/arturhaddad/projects/divulgai-frontend/node_modules/video-react/lib/components'
```

Any hints on how to solve it?

**Comment by arturhaddad** [comment]
It was a conflict problem because i was using both npm and yarn.

**Comment by mondaychen** [comment]
It might relate to a similar issue #237 

Can you check if the latest version 0.13.5 fixes the problem?

**Comment by arturhaddad** [comment]
Actually the problem was that i was using npm and yarn. I removed npm lockfile and node_modules folder, ran yarn and it fixed.
