### ISSUE TITLE
The playbackRate item show inconsistant when video source changed

### ISSUE THREAD

**Issue by Yezzle** [video-react/video-react#243]
The bug turns out when I change the playbackRate to 2 and then change the video resource and reload.
![image](https://user-images.githubusercontent.com/29877797/54191528-11537500-44f1-11e9-8c44-444e17814dad.png)

**Comment by Yezzle** [comment]
The current video playbackRate is 1 but '2x' item is bright

**Comment by mondaychen** [comment]
I'm not able to reproduce this issue. Could you provide me a demo in codesandbox?
