### ISSUE TITLE
Is it possible to play 360° videos ?

### ISSUE THREAD

**Issue by PierreSachot** [video-react/video-react#249]
Hi everyone, 
I would like to play 360° videos, is it possible with video-react or should I develop this function ?

Thanks a lot.

**Comment by mondaychen** [comment]
If you are asking about 360° videos like Youtube's feature, where you can drag around and see everything, the answer is, no, we don't have such support yet. If you believe you can build this function based on video-react, we'd certainly welcome the contribution. (but IMO it's so much work maybe it should be its own repo lol)

**Comment by PierreSachot** [comment]
Ok thanks for the response, I will tell you if I get something :)
