### ISSUE TITLE
Replay/Froward Control - Triggers New HTTP Requests

### ISSUE THREAD

**Issue by paolavness** [video-react/video-react#25]
Hi there, I hope this finds you well.

### We're serving restricted access content with video-react, requiring pre-signed URLs (with short expire times - 10sec ) to give users access. When the video is playing and a user watches thru, everything is fine. When the user tries to fast forward or replay backward - clicking the Replay or Forward buttons a few times in succession - a new HTTP request is made to the video. In our case this fails because the URL has now expired.

- version `#0.7.3`
- browser: `Chrome 57.0.2987.98`

### Steps to reproduce issue
Play a video using below settings - hit fastforward or rewind buttons in quick success. In this case, it was an 1hr MP4 video 

### Steps to reproduce

```
                    <Player ref="player" 
                            muted       = {muted} 
                            autoPlay    = {autoPlay} 
                            startTime   = {startTime} 
                            >
                        <BigPlayButton position="center" />
                        <source src={videoSrc} />
                        <LoadingSpinner /> 
                        <ControlBar autoHide={false} >
                            <ReplayControl seconds={10} order={1.1} />
                            <ForwardControl seconds={10} order={1.2} />
                            <CurrentTimeDisplay order={4.1} />
                            <TimeDivider order={4.2} />
                            <PlaybackRateMenuButton
                                rates={[0.25, 0.5, 1, 1.25, 1.5]}
                                order={7.1}
                            />
                            <VolumeMenuButton vertical={true} />
                        </ControlBar>
                        <Shortcut shortcuts={this.newShortcuts} />
                    </Player>
```

### Expected behaviour
Expect no additional HTTP request to be made to (unless video is a multipart HLS stream). 

### Actual behaviour
Multiple HTTPS requests being made on video fastforward and rewind

**Comment by JimLiu** [comment]
Video-React is base on the HTML5 video player, it just calls the HTML5 video APIs, it won't send new http request by itself, so this problem is out of its control.
