### ISSUE TITLE
Doesn't work on deployed site

### ISSUE THREAD

**Issue by realitybreakdown** [video-react/video-react#252]
I'm having an issue where it works fine on my browser (local host), but when visiting the site after deployment, it looks very weird. 

What it looks like on the browser:
<img width="559" alt="Screen Shot 2019-03-19 at 5 01 14 PM" src="https://user-images.githubusercontent.com/28129478/54649858-196b6180-4a69-11e9-9f63-486bb7ee47d3.png">

What it looks like after being deployed: 
<img width="621" alt="Screen Shot 2019-03-19 at 5 01 26 PM" src="https://user-images.githubusercontent.com/28129478/54649865-1bcdbb80-4a69-11e9-91b2-74c76419a793.png">

 - macOS Mojave
 - Chrome 72
 - Version [e.g. 0.13.2]

**Comment by mondaychen** [comment]
You have bad css files on your deployed site.

I'm closing this because I'm pretty sure it's not related to video-react itself.
