### ISSUE TITLE
I can't get the real status of paused

### ISSUE THREAD

**Issue by hangpage** [video-react/video-react#259]
**Describe the bug**
I clicked the play button, and the pause status remained unchanged.

**To Reproduce**
1. click play button
2. setInterval( () => {
         console.log(this.ref.getState().player)
       }, 2500)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. 0.13.2]

**Additional context**

**Demo**
 
https://codesandbox.io/s/0xn619734p

**Comment by mondaychen** [comment]
Please fork the codesandbox to provide a demo
