### ISSUE TITLE
Clickable not working in latest Chrome

### ISSUE THREAD

**Issue by pmkhoa** [video-react/video-react#262]
**Describe the bug**
`clickable` and `dblclickable` from Shortcut are not working in Chrome browser. This cause clicking on the video not playing or pausing.

**To Reproduce**
1. Open Google Chrome (Version 73.0.3683.103 (Official Build) (64-bit))
2. Go to: https://video-react.js.org
3. Click play example video on home page.
4. Click or double click on the video has no effect.

**Expected behavior**
Click or doubleclick on the video should be working as described in Shortcut component.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version: Version 73.0.3683.103 (Official Build) (64-bit)

**Additional context**
This currently working in Firefox or Safari, but not Chrome. I suspect this issue related to t chrome shadow root on video element.

**Comment by jdcumpson** [comment]
If it helps, the way that I'm working around this is setting up an `onClick` listener on the `manager.video.video` element that calls `manager.rootElement.focus()` and it seems to make things work. Looks like it could be a focus management issue.

(I am using `componentDidUpdate` because I am not mounting the player on first render)

```
constructor(props) {
    super(props)
    this.playerRef = React.createRef()
  }

handleVideoClick = (event) => {
    this.playerRef.current.manager.rootElement.focus()
  }

  componentDidUpdate(prevProps, prevState) {
    const video = _.get(this.playerRef, 'current.manager.video.video')
    if (!video) {
      return video
    }
    video.removeEventListener('click', this.handleVideoClick)
    video.addEventListener('click', this.handleVideoClick)
  }

  componentWillUnount() {
    const video = _.get(this.playerRef, 'current.manager.video.video')
    if (!video) {
      return video
    }
    video.removeEventListener('click', this.handleVideoClick)
  }
```

**Comment by mondaychen** [comment]
Thanks for reporting! I'm on it.

**Comment by mondaychen** [comment]
I think this is because the latest chrome no longer consider `video` as a focusable element by default

**Comment by pmkhoa** [comment]
Sounds good. Thank you for looking into it.
