### ISSUE TITLE
Display custom buttons on click

### ISSUE THREAD

**Issue by misteryyy** [video-react/video-react#263]
Hello, 
is there any way how I can display my custom menu when I click on the video canvas? I  dont want to pause or play the video. Just toggle my custom menu when I am clicking on the video canvas. 

Do you have any idea how to achieve this?
Thanks for ideas, 
Josef

**Comment by mondaychen** [comment]
Hi. I think you can use a state to store a boolean such as `shouldDisplayCustomMenu` in the parent component, and then inside your jsx you can do:

```
...
<ControlBar>
  { this.state.shouldDisplayCustomMenu && <CustomMenu /> }
</ControlBar>
```
