### ISSUE TITLE
ERROR in [copy-webpack-plugin] unable to locate './dist' at 'video-react/dist'

### ISSUE THREAD

**Issue by OhIAmFine** [video-react/video-react#264]
**Describe the bug**
I follow the instruction in README, `npm install` and `npm start`, but when webpack build the application ,it occured this error `ERROR in [copy-webpack-plugin] unable to locate './dist' at '/Users/chenjunsong/Desktop/personal/video-react/dist'`

**Screenshots**
![image](https://user-images.githubusercontent.com/10390004/56486033-e6553b80-6508-11e9-975d-10b4eed2643a.png)

**Desktop (please complete the following information):**
 - OS: mac pro
 - Browser :the lastest Chrome

**Comment by mondaychen** [comment]
Are you trying to build video-react itself, or use video-react in your own project?

**Comment by wimpykatana** [comment]
hello,
i have same issue when i try to build video-react itself, i just add dist folder inside your video-react folder and problem solve. :)

**Comment by OhIAmFine** [comment]
@wimpykatana  Thank your answer, I have resolved this issues, just 

```
> npm run build
> npm run start
```
