### ISSUE TITLE
请问ControlBar上的播放/暂停按钮有点击事件吗？

### ISSUE THREAD

**Issue by Sakurakawa** [video-react/video-react#265]

**Comment by mondaychen** [comment]
We do not currently expose `onClick` for `PlayToggle` component. I recommend using `subscribeToStateChange` to check the player's status if you need to do additional operation when user pause/play video.

**Comment by Sakurakawa** [comment]
> We do not currently expose `onClick` for `PlayToggle` component. I recommend using `subscribeToStateChange` to check the player's status if you need to do additional operation when user pause/play video.

Hi! Thanks for replying. I just want to send data like playtime to my backend by axios after clicking pause/play button. Is there any other way to do that?

**Comment by mondaychen** [comment]
Do you mean you need to distinguish button clicking and other sources when collecting this data?

**Comment by Sakurakawa** [comment]
I had already resolved it. Thanks.
