### ISSUE TITLE
重复自动播放超短视频时的问题

### ISSUE THREAD

**Issue by dicklwm** [video-react/video-react#27]
### Issue description

- version `0.7.3`
- browser: `Chrome 57.0.2987.110 (64-bit)`

### Expected 
1. 我想在视频播放期间把ControlBar隐藏了，就是不再会显示的那种，因为我播放的是只有几秒钟的视频，而且会重复自动播放，所以每次播放后都会有一条ControlBar在那。
2. 自动重复播放时，LoadingSpinner不再显示。因为每次重播放时，都会弹出一个LoadingSpinner，我也不想要他
3. 我不想让他点击视频暂停或播放

- 请问这种情况在现在的版本有相对的方案吗？如果没有可以扩展一下吗？
- 欢迎PR吗？

**Comment by JimLiu** [comment]
这种情况其实你直接使用原生的html5 video component不是更好？

我需要确认下是否支持你的需求，晚些时候给你回复

**Comment by JimLiu** [comment]
应该是支持的
```html
      <Player
        src="https://media.w3.org/2010/05/sintel/trailer_hd.mp4"
      >
        <ControlBar disabled />
        <Shortcut disabled />
        <LoadingSpinner disabled />
      </Player>
```

**Comment by dicklwm** [comment]
用得插件多，思想都固化了。用原生的解决需求了，感谢了~
