### ISSUE TITLE
can you add a custom user-agent when calling a live streaming link

### ISSUE THREAD

**Issue by hamdi-islam** [video-react/video-react#271]
Hello,

I was trying to use your library with one of my projects where i wanted to display a live streaming content based on a url, the only problem was that the server had to receive a custom user-agent string.

So for more details, the link was like the following:
http://example.com/channel/anonymous.ts

and the custom user-agent was something like user-agent: "someText"

is there a way in your library that would allow me to play that live stream ? thank you

**Comment by mondaychen** [comment]
I think user-agent is controlled by the browser. I did find something on stackoverflow https://stackoverflow.com/questions/23248525/setting-a-custom-useragent-in-html-or-javascript/44367690

**Comment by mondaychen** [comment]
I'm closing this since it's not related to video-react itself
