### ISSUE TITLE
Space button starts triggering Full Screen mode

### ISSUE THREAD

**Issue by damiench** [video-react/video-react#276]
**Describe the bug**
Space button starts triggering Full Screen mode after manual clicking on full screen button in control bar.

**To Reproduce**
1. Click Full Screen button in ControlBar.
2. Toggle space button on keyboard.
3. Video leaves Full Screen state.
4. All others Spacebar clicks will toggle isFullscreen state.

**Expected behavior**
Space will only toggle play/pause state.

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra 10.13.6 (17G7024)
 - Browser: Chrome
 - Version: 74.0.3729.169

**Comment by mondaychen** [comment]
Confirmed bug. I'll fix it as soon as possible.

Thanks for reporting!

**Comment by damiench** [comment]
Thank you for fixing bug!
