### ISSUE TITLE
Flash fallback for internet explorer 11 in windows 7 on HLS

### ISSUE THREAD

**Issue by jsanadev** [video-react/video-react#277]
**Is your feature request related to a problem? Please describe.**
Yes, it throws AUDIO/VIDEO unknow mimetype

**Describe the solution you'd like**
To have the chance to use flash fallback on this environment

**Describe alternatives you've considered**
video.js provides flash fallback

**Comment by mondaychen** [comment]
If there's an existing Flash project that can support HLS elegantly, we can consider integrating it to provide such an option. Otherwise, we will not be able to do it, because no one in the team has expertise in Flash development.
