### ISSUE TITLE
Replay/Forward Control clicked or drag the progress bar, the video will restart

### ISSUE THREAD

**Issue by eruca** [video-react/video-react#283]
I found the demo, it work fine.
any reason?
does it has any relationship with the server? my server is the http server(golang).
```js
<Player
       fluid={false}
       width="100%"
       height="100%"
       playsInline
       poster="/assets/poster.png"
       src={`http://localhost:9000/download/${name}`}
>
       <ControlBar>
              <ReplayControl seconds={10} order={1.1} />
              <ForwardControl seconds={30} order={1.2} />
              <CurrentTimeDisplay order={4.1} />
              <TimeDivider order={4.2} />
              <PlaybackRateMenuButton rates={[5, 2, 1, 0.5, 0.1]} order={7.1} />
              <VolumeMenuButton disabled />
       </ControlBar>
</Player>
```

**Comment by mondaychen** [comment]
It's probably related to your video server not serving the video as a stream. Can you set up a native HTML `<video>` tag to see if it's related to video-react?

**Comment by eruca** [comment]
I agree with you. I just serve the mp4 as a file not a stream.
I'm a beginner to video things, could you give me a tip how to build the server end(schema), just like you did in the demo?

**Comment by eruca** [comment]
thanks for your quick answer!
I have fixed it using the nginx!
