### ISSUE TITLE
ControlBar disappear after 5 seconds drag on mobile devices

### ISSUE THREAD

**Issue by Diwatt** [video-react/video-react#289]
**Describe the bug**
When you drag the seekbar the dragmove doesn't seems to change userActivity so after 5 seconds the ControlBar will disappear

**To Reproduce**
Just start to drag the the seek dot and hold it and move it for 5 seconds.

**Expected behavior**
It should restart timer of the userActivity state so the controlbar won't fade out.

**Video**
Here a sample video
https://www.youtube.com/watch?v=SFnGM03RLmw&feature=youtu.be

The video is on my own integration but you can reproduce the same bug on https://video-react.js.org/ samples on any mobile devices.

And thank you for your great project !

**Comment by mondaychen** [comment]
Thanks for reporting! Yes, I think resetting timer when dragging should fix this issue. I'll try to fix it when I have time later this week.
