### ISSUE TITLE
我们的项目里面里面也要配置sass编译吗

### ISSUE THREAD

**Issue by uixdk** [video-react/video-react#29]
### 我们的项目里面里面也要配置sass编译吗
 上周五，lib/index.js 文件第8行增加 require('../styles/scss/video-react.scss');    
这样的话我们的项目里面
 import { Player, ControlBar } from 'video-react';
如果我们的webpack里面没有配置sass的话，就会报错。
所以我建议删除 lib/index.js 文件第8行 require('../styles/scss/video-react.scss');   
并在package.json里面加入
"style": "dist/video-react.min.js",

**Comment by JimLiu** [comment]
汗，我会马上调整一下

**Comment by JimLiu** [comment]
已更新

**Comment by uixdk** [comment]
我还是有个建议，在package.json里增加一个style节点。这样的话我们的项目里面就会自动引入css。
"style": "dist/video-react.min.js",

**Comment by JimLiu** [comment]
会尽快加上
