### ISSUE TITLE
Does this support progressive loading? (question)

### ISSUE THREAD

**Issue by darklightblue** [video-react/video-react#294]
Hi, I'm very new with video manipulation and I was wondering if this library supports progressive loading?

Like.. it doesn't fully download the file from the server but instead download it bit by bit (stream).

I saw the examples they're being loaded instantly - but this might be also caused by the fast internet. So I can't really be sure until I ask this. Thank you.

**Comment by mondaychen** [comment]
This project is a react wrapper for html `<video>` tag. So yes it supports streaming.
