### ISSUE TITLE
Does video-react support Safari?

### ISSUE THREAD

**Issue by Riasets** [video-react/video-react#295]
**Describe the bug**
Video doesn't work on safari

**To Reproduce**
1. Go to page with video-react (e.g.  https://video-react.js.org/)
2. Click on 'play'

**Expected behavior**
Video should play

**Screenshots**
![image](https://user-images.githubusercontent.com/35662845/61404615-7aecf100-a8e0-11e9-9dc6-11087aa746ae.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.3
 - Browser Safari 12.0.3(14606.4.5)
 - Version 0.14.0

**Comment by mondaychen** [comment]
I checked it on Safari and could not reproduce your issue. It definitely supports Safari
