### ISSUE TITLE
How to re-render component when new media url is passed as prop

### ISSUE THREAD

**Issue by pawelotto** [video-react/video-react#296]
I need to re-render the Player component on a prop update. Right now, the props are being passed down and the new source url appears in DOM, but the video playing is the old one.

How do I re-render the Player so that it shows the new video?

Thanks

**Comment by pawelotto** [comment]
OK I resolved it by replacing <source> with <Video> component.

**Comment by nirajrajgor** [comment]
You can use the `this.player.reload()` functionality. It's also mentioned in the documentation as follows.
`
this.state = {
      playerSource: 'https://media.w3.org/2010/05/sintel/trailer_hd.mp4',
    };

componentDidUpdate(prevProps, prevState) {
    if (this.state.playerSource !== prevState.playerSource) {
      this.player.load();
    }
  }

  updatePlayerInfo() {
    const { inputVideoUrl } = this.state;
    this.setState({
      playerSource: inputVideoUrl
    });
  }`
