### ISSUE TITLE
How to add token into video tag request header?

### ISSUE THREAD

**Issue by matthewgan** [video-react/video-react#302]
I am trying to play secured videos after user login.
So I have the token and need to add it into video request, 
How can I do that? and how can I do it in video-react?

**Comment by mondaychen** [comment]
You might find this article helpful https://blog.peer5.com/practical-approaches-for-securing-your-video-streams/

I'm closing this since it's not related to video-react

**Comment by lmiol** [comment]
> You might find this article helpful https://blog.peer5.com/practical-approaches-for-securing-your-video-streams/
This is link doesnt help.
that guy ask about header through video-react

Example of react-pdf library header
{ url: ${API_URL} + '/service/file/' + ${block.presentation.uuid},
 httpHeaders: { 'Authorization': bearer token }
            }
