### ISSUE TITLE
[Update] Browsers support

### ISSUE THREAD

**Issue by nathan5x** [video-react/video-react#303]
I'm in the process of evaluating multiple video players, video-react is one of them. One of the key criteria is the **browser support.** It would be great if there is a table in ReadMe to describe the list of browsers supported (if possible with features). 

Not as detailed as this one, but something high-level.
https://github.com/google/shaka-player#platform-and-browser-support-matrix

Thank you!

**Comment by mondaychen** [comment]
Will do.

**Comment by mondaychen** [comment]
Before I commit the changes, the basic idea is we support latest versions of all major browsers (Chrome, Safari, Firefox, Edge, IE11). But to be honest it's less frequently tested on Windows (especially IE11).

**Comment by mondaychen** [comment]
done in #308

**Comment by nathan5x** [comment]
Thank you @mondaychen ! Really appreciate it. :)
