### ISSUE TITLE
prevent video download

### ISSUE THREAD

**Issue by VamuveTV** [video-react/video-react#304]
How to prevent the video from being downloaded while playing it through the web browser ? I mean, how to prevent that others steals the video that is being showend on the player ? There are several video grabbers out there, but how to prevent it ? Does the player have a security routine for that ?

**Comment by JimLiu** [comment]
That's out of `video-react`'s scope you can try some livestreaming solution like hls
https://www.dacast.com/blog/hls-streaming-protocol/
