### ISSUE TITLE
onClick function for BigPlayButton

### ISSUE THREAD

**Issue by skjo0c** [video-react/video-react#307]
**Is your feature request related to a problem? Please describe.**
Not able to make a custom function when clicking big play button. I have a embed player on react-native in which I would like to make it full screen when clicking on BigPlayButton.

**Describe the solution you'd like**
A prop that could be use as onClick function.

**Comment by skjo0c** [comment]
any update on this?

**Comment by JunlinZhu-Tommy** [comment]
https://github.com/video-react/video-react/blob/master/src/components/BigPlayButton.js#L31
it fairly easy to customize your own <BigPlayButton> with the onClick function you mentioned, or you can subscribe the redux state changes Player and went to fullscreen once status `hasStarted` become true.

**Comment by skjo0c** [comment]
I actually used hasStarted state

**Comment by JunlinZhu-Tommy** [comment]
@skjo0c cool, case solved?

**Comment by skjo0c** [comment]
yes! Thanks :)
