### ISSUE TITLE
Is there a way to disable video play?

### ISSUE THREAD

**Issue by n1th1l** [video-react/video-react#309]
I want to disable video play when showing all videos, on clicking I'm rendering a modal, where I can allow play on button click

**Comment by mondaychen** [comment]
Do you mean you want to not auto-play?

**Comment by elfaza** [comment]
have you found the answer yet? if you have, will you share the answer?

**Comment by justsolarry** [comment]
A solution is following:
- Pass a source url to the component as props. 
- When you want to disable video play, update and set that source url to be an empty string
- Hide the play button on the video.

`
<BigPlayButton
          position='center'
          className={ hidePlay ? 'hide-play' : 'show-play' }
     />
`
