### ISSUE TITLE
mov video format is not playing

### ISSUE THREAD

**Issue by vinothkumarJM** [video-react/video-react#314]
mov video format above 1 mb is not playing in this player but below 1 mb video is playing perfectly in this format I don't know whether it has specific size is allow to play the video. 

The same video is streaming and playing in all browser directly. 

Please give some solution for this.

**Comment by mondaychen** [comment]
I'd suggest you to check your server configuration. It might have a limitation on this.

**Comment by hzburki** [comment]
I have the same issue. When I upload a new video in **mov** format to the browser which is **more than 1MB** in size, nothing appears when I play it. Videos **below 1 MB size run fine**. 

> **Note: This is before the file is sent to the server.**
