### ISSUE TITLE
微信以及微博浏览器播放按钮无法显示

### ISSUE THREAD

**Issue by MagicLizi** [video-react/video-react#32]
微信以及微博浏览器，第一次打开页面的时候无法显示播放按钮，
微信浏览器可以通过以下代码解决。。微博就没办法了

```
WeixinJSBridge.invoke('getNetworkType', {}, e=> {
        this.refs['player'].load();
      });
```

![wechatimg2](https://cloud.githubusercontent.com/assets/17176223/25561582/1c8138ee-2da2-11e7-9369-a99c510501db.jpeg)

**Comment by JimLiu** [comment]
试过，实在搞不定，欢迎提交PR
