### ISSUE TITLE
Not able to play mpeg 4 (.mpg) files in player

### ISSUE THREAD

**Issue by shukanshah** [video-react/video-react#325]
I have mpeg4 video files. I am not able to play with player. If I am changing mp4 to mpg then its working. Can anyone tell me here what's wrong here?

this file is not working
![working](https://user-images.githubusercontent.com/48135506/70273891-534fd580-1768-11ea-86df-3d77026621ed.PNG)

this file has same codec details but its working
![not working](https://user-images.githubusercontent.com/48135506/70273792-200d4680-1768-11ea-84a4-ca9507bf49a5.PNG)

Any help much appreciate.

**Comment by JunlinZhu-Tommy** [comment]
https://stackoverflow.com/questions/14929516/is-there-a-way-to-play-mpeg-videos-in-html5
