### ISSUE TITLE
Not working in IE11 on Windows 7

### ISSUE THREAD

**Issue by ebhoren** [video-react/video-react#33]
This plugin is not working at all in IE11 on Windows 7.
I've tried the installation guide on https://video-react.js.org/ and it doesn't work.

It work on Chrome, but not in IE11.
The app compile correctly. I'm using create-react-app to start a boilerplate projet.

## Step to reproduces
Type these command into a Terminal window
1. create-react-app my-app
2. cd my-app
3. npm install --save video-react redux
4. npm start

Edit **src/App.js** to
```
import React, { Component } from 'react';
import { Player } from 'video-react';
import logo from './logo.svg';
import './App.css';
import "./node_modules/video-react/dist/video-react.css";

class App extends Component {
  render() {
    return (
      <div className="App">
        <div className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h2>Welcome to React</h2>
        </div>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
        <Player playsInline autoPlay src="https://media.w3.org/2010/05/sintel/trailer_hd.mp4" />
      </div>
    );
  }
}

export default App;
```

Save the file and view result in your browser

**Comment by JimLiu** [comment]
Sorry I have no win7 to test it currently, will keep an eye on it

**Comment by ebhoren** [comment]
Check this out:
https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by JimLiu** [comment]
Sorry I have no VM too.
Tested from Win10 + IE11,  it works well.

Any error message from the console?

**Comment by ebhoren** [comment]
I'm not talking about IE11 in Win10. I'm talking about IE11 on Win7.
There is no error logged in console.

I don't know how you tested IE11 on Windows 10 since IE11 as switched to IE Edge on Windows 10.

Anyway, i've switched my code to use video.js instead.
