### ISSUE TITLE
Video doesn't update when seeking

### ISSUE THREAD

**Issue by Yoruba** [video-react/video-react#34]
If you seeking through the video the video is not updating while seeking.
The video is updated after you stop with seeking.

In this example the video is update while seeking.
[See this example](http://mderrick.github.io/react-html5video/)

Thanks, Adri

**Comment by JimLiu** [comment]
Yes, this is by design, it's paused while seeking.

**Comment by Yoruba** [comment]
Could you make it play by design?
Or make this optional?

Thanks Adri

**Comment by JimLiu** [comment]
I'm kind of busy recently, no time for that.

If you or anyone else would like to create a PR for that would be great.

add a property to enable that.
https://github.com/video-react/video-react/blob/master/src/components/control-bar/SeekBar.js#L70-L74

Adding these lines to `handleMouseMove` can seek while moving

**Comment by dsslimshaddy** [comment]
play while seeking is bad idea that will cause bad performance.
