### ISSUE TITLE
video-react autoplay wasn't work

### ISSUE THREAD

**Issue by Straw94** [video-react/video-react#364]
```javascript
    <Player
      autoPlay
      src="https://media.w3.org/2010/05/sintel/trailer_hd.mp4"
    >
    </Player>
```

**Comment by brmscheiner** [comment]
I have also been experiencing issues with the autoPlay prop... _sometimes_ it works and sometimes the video just stalls on the first frame until I click it. 

The one clue I might be able to provide is when I hard refresh the page autoPlay fails, when I navigate to the page in question via react-router autoPlay succeeds. Chrome 83.0.4103.116 on OSX

**Comment by disrael** [comment]
Could this be https://www.theverge.com/2018/3/22/17150870/google-chrome-autoplay-videos-sound-mute-update?

**Comment by huihui925** [comment]
ideo-react autoplay wasn't work

**Comment by YardWill** [comment]
You can view Chrome autoplay policy on this [page](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#new-behaviors). Or you can provide a sandbox link if there has some reason out of 'Chrome autoplay policy'.
