### ISSUE TITLE
无法播放HEVC编码的mp4格式的视频(播放效果，只有音频没有视频)

### ISSUE THREAD

**Issue by minsion** [video-react/video-react#381]
1.视频地址
https://gw.alicdn.com/bao/uploaded/LB1l2iXISzqK1RjSZFjXXblCFXa.mp4?spm=taofed.bloginfo.blog.1.309f5ac8RHpUwE&file=LB1l2iXISzqK1RjSZFjXXblCFXa.mp4
2.浏览器Chrome
3.在Chrome浏览器中打开视频，只有音频没有视频

**Comment by tommy1994111** [comment]
https://caniuse.com/hevc
Chrome is not currently supported.

**Comment by YardWill** [comment]
Chrome MSE is not support hevc. You can use wasm with FFmpeg to decode by yourself.
