### ISSUE TITLE
attribute width and height is not working

### ISSUE THREAD

**Issue by BijayRai** [video-react/video-react#39]
width	number	-	Video width
height	number	-	Video height

As per doc these attribute doesnot work or say there is no changes on video width and height..

```
<Player playsInline width={100} height={50}>
<source src="https://media.w3.org/2010/05/sintel/trailer_hd.mp4"/>
<ControlBar>
    <PlaybackRateMenuButton rates={[2,1.5,1]} order={7.1} />
    <VolumeMenuButton disabled />
</ControlBar>
</Player>
```

**Comment by JimLiu** [comment]
Sorry for late reply.
You need to set `fluid` attribute as `false`, I'll update document with that.

```jsx
    <Player playsInline fluid={false} width={100} height={50}>
      <source src="https://media.w3.org/2010/05/sintel/trailer_hd.mp4"/>
      <ControlBar>
          <PlaybackRateMenuButton rates={[2,1.5,1]} order={7.1} />
          <VolumeMenuButton disabled />
      </ControlBar>
    </Player>
```

**Comment by BijayRai** [comment]
Thanks @JimLiu  for your reply.. Now it works 👍

**Comment by kontomierz** [comment]
I tried the following:

```javascript
<Player playsInline fluid={false} width={320} height={320}>
  <source src="https://media.w3.org/2010/05/sintel/trailer_hd.mp4"/>
</Player>
```

but the player is still displaying large video. Also, I checked <video> tag attributes in generated html amd there were no width nor height attributes (not sure if it is relevant though).

Can you suggest any other ways?
