### ISSUE TITLE
How can config to support rtmp/flv

### ISSUE THREAD

**Issue by pcgpcgpcg** [video-react/video-react#40]
How can config to support rtmp/flv

**Comment by JimLiu** [comment]
Check this: https://github.com/video-react/video-react/issues/17#issuecomment-279717168

**Comment by pcgpcgpcg** [comment]
3q! but flv.js not support rtmp.....      and no   video.js for react

**Comment by pcgpcgpcg** [comment]
since video-react heavily on video.js  , there is possibility for rtmp/flv?

**Comment by JimLiu** [comment]
video-react only uses the style of video.js 
you need to find a lib like flv.js which supports rtmp.

**Comment by pcgpcgpcg** [comment]
ok , Thanks!
