### ISSUE TITLE
Loading Spinner Appears Indefinitely in IE11

### ISSUE THREAD

**Issue by thejamespower** [video-react/video-react#43]
### Issue description
`.video-react-waiting` class not removed in IE, causing loading spinner to remain indefinitely.

- version 0.8.5
- browser: Internet Explorer 11

### Steps to reproduce issue

1. Seek video.
2. Loading spinner appears while video buffers.
3. Video finishes buffering.
4. Loading spinner remains even after playback resumes.

This works fine in all other tested browsers.

### Expected behaviour
Loading spinner should disappear when loading complete.

### Actual behaviour
 Loading spinner remains

### Demo
You can fork from this template and add your code
https://jsfiddle.net/jimliu/wcnqzwgs/

JSFiddle doesn't even work...

**Comment by JimLiu** [comment]
I'm using Mac currently, will take a look when I use the windows 10.

**Comment by JimLiu** [comment]
Could you have a try with the new v0.8.8?
Thanks

**Comment by thejamespower** [comment]
Will try look at this asap.

**Comment by bukso** [comment]
I have the error:

There is still an error:

×TypeError: Object doesn't support property or method 'find'
Anonymous function
D:/sourcetree/vasko/video-module/node_modules/video-react/lib/utils/index.js:86
83 | return children.filter(function (e) {
84 | return !e.props.disabled;
85 | }).concat(defaultChildren.filter(function (c) {

86 | return !children.find(function (component) {
87 | return component.type === c.type;
88 | });
89 | })).map(function (element) {
