### ISSUE TITLE
Getting height and width from state

### ISSUE THREAD

**Issue by kenanchristian** [video-react/video-react#44]
I've been trying to get the player height & weight with this code snippet
```js
let {player : playerState} = this.player.getState();
let { currentTime, height, width } = playerState;
```
But it always give me 0 even though the player have height & width, this is my player
```js
<Player ref={(player) => {this.player = player}} autoPlay fluid>
  <HLSSource
      isVideoChild
      src={video.play_url}
  />
</Player>
```

Or is it only can get the height & width that I set via props?

**Comment by JimLiu** [comment]
if you set `fluid` attribute, you could not get the width and height, but you could get the `videoWidth` and `videoHeight`

Doc: https://video-react.js.org/components/player/

**Comment by kenanchristian** [comment]
@JimLiu Tried removing the `fluid` attribute, but still can't get the width & height
I need the player width & height, so `videoWidth` & `videoHeight` isn't correct
Or both are the same thing?

Btw, found a bit of typo on the docs
![image](https://user-images.githubusercontent.com/11202498/29865026-9fbc25d2-8d9e-11e7-87cd-3b84cfaf7d63.png)

**Comment by kenanchristian** [comment]
After some debugging, I found out that I need to set the fluid to false to remove it, not just removing it from the attributes, and if I need to get the height/width when the fluid attribute is there I can use this `this.player.video.video.clientHeight`.
