### ISSUE TITLE
Problem configuring width and height of the video player

### ISSUE THREAD

**Issue by popo63301** [video-react/video-react#45]
I have troubles configuring the size of my player. So here is my code.

```
        <Player
        playsInline
        fluid={false}
        src="https://media.w3.org/2010/05/sintel/trailer_hd.mp4"
        width={100}
        height={50}
      />
```

I still have always a big size whatever I do changing width and size and even changing fluid. What can I do?

**Comment by popo63301** [comment]
I've figured out how to change the size, just imported the css first.

`import "video-react/dist/video-react.css";`

It would have been better if it was more clear. Maybe you can add some explanation in the doc about that. ☺️

**Comment by JimLiu** [comment]
We have the document about css in Readme
https://github.com/video-react/video-react#installation

Anyway, it could be better. 

Thanks

**Comment by wandonye** [comment]
I tried
```
import "node_modules/video-react/dist/video-react.css";
```

```
import "video-react/dist/video-react.css";
```

Neither worked.
My folder structure is like this:

my_project/
--app/
----components/
----app.global.css
....
--node_modules/


Also tried adding 

```
@import "~video-react/styles/scss/video-react"; // or import scss
```

to  `app.global.css`. It then report error.

**Comment by JimLiu** [comment]
@wandonye  Could you check the css path from your node_modules/video-react ?
