### ISSUE TITLE
Set interval with beginning and end time of video

### ISSUE THREAD

**Issue by popo63301** [video-react/video-react#46]
I want to suggest you a new feature for this video player. It's interval. So, basically, we can set a beginning time and end time for an interval like in youtube videos. 

Here is an example of a video with a beginning interval (and the end is the end of the video): https://9gag.com/tv/p/aePQ7q/game-of-thrones-theme-song-created-in-garageband

I wish we can have the possibility to set both beginning and end interval very precisely. I did manage something with handleStateChange(state, prevState) but the thing is it's not accurate enough. If I want to catch exactly 20 s for instance it won't work. It will be sometimes 20.1XX or 20.6xx depends when the store updates. Would be curious to know how we can implement this.

**Comment by JimLiu** [comment]
Hi 
Thanks for the suggestion

Sorry I have no plan to implement that, but you still can write a plugin for that.

Like this: https://video-react.js.org/customize/customize-source/

Thanks

**Comment by yoDon** [comment]
For others who happen upon this thread while searching, the Player does have a startTime property that can be used to set a custom start time for the video, in seconds.

**Comment by JimLiu** [comment]
@yoDon 
You are right, there is a sample code:
https://video-react.js.org/components/replay-control/

```jsx
import React from 'react';
import { Player, ControlBar, ReplayControl} from 'video-react';

export default (props) => {
  return (
    <Player
      autoPlay
      poster="/assets/poster.png"
      startTime={300}
      src="http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4"
    >
      <ControlBar autoHide={false}>
        <ReplayControl seconds={5} order={2.1} />
        <ReplayControl seconds={10} order={2.2} />
        <ReplayControl seconds={30} order={2.3} />
      </ControlBar>
    </Player>
  );
};
```

**Comment by mark-steven-au** [comment]
So anyone know of a way to have an EndTime={25} 
Or a run time which would effectively give you and end time?

**Comment by HitaishLokeshEntr** [comment]
Does anyone have the answer to what @mark-steven-au has asked for ? 
I am in need of the endTime as well.
