### ISSUE TITLE
ControlBar className from property doesnt appear

### ISSUE THREAD

**Issue by bukso** [video-react/video-react#48]
### Steps to reproduce

1. add className to the controlbar `<ControlBar className="my-class"></ControlBar>`

### Expected behaviour
Then in the control bar div should appear `my-class`

### Actual behaviour
in control bar appear class `"className"` like `<div class="className"...`

**Comment by JimLiu** [comment]
Thanks for reporting that, please update to v0.8.8 and verify it.
