### ISSUE TITLE
Video-React does not support IE

### ISSUE THREAD

**Issue by bukso** [video-react/video-react#49]
In IE you have an error:

Object doesn't support property or method 'find'

and the player crashes

**Comment by JimLiu** [comment]
Thanks for reporting that, please update to v0.8.8 and verify it.

**Comment by bukso** [comment]
There is still an error:

×TypeError: Object doesn't support property or method 'find'
Anonymous function
D:/sourcetree/vasko/video-module/node_modules/video-react/lib/utils/index.js:86
  83 | return children.filter(function (e) {
  84 |   return !e.props.disabled;
  85 | }).concat(defaultChildren.filter(function (c) {
> 86 |   return !children.find(function (component) {
  87 |     return component.type === c.type;
  88 |   });
  89 | })).map(function (element) {

**Comment by ronnyandre** [comment]
@bukso I had the same issue, but resolved it with babel-polyfill package.
