### ISSUE TITLE
播放器自动全屏

### ISSUE THREAD

**Issue by jobn123** [video-react/video-react#5]
你好，现在有一个需求是，我这边监听到横屏或竖屏后自动全屏播放，请问有没有暴露全屏的接口呢，比如说`this.refs.player.fullscreen`

谢谢

**Comment by jobn123** [comment]
全屏操作好像必须是用户操作才可以

`Failed to execute 'requestFullScreen' on 'Element': API can only be initiated by a user gesture.`

**Comment by JimLiu** [comment]
抱歉才看到，这种情况建议你可以网页内全屏，也就是类似于
`position: fixed;width: 100%;height: 100%;`
这种方式
