### ISSUE TITLE
How to add source youtube?

### ISSUE THREAD

**Issue by huynguyentdt** [video-react/video-react#53]
### Issue description
i wanto add source youtube into player component
- version `#x.x.x`
- browser: `name-version`

### Steps to reproduce

1. step1
2. step2
3. step3

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Demo
You can fork from this template and add your code
https://jsfiddle.net/jimliu/wcnqzwgs/

**Comment by JimLiu** [comment]
Sorry, this component does not support youtube
