### ISSUE TITLE
Safari 11 autoplay + bigPlayButton - doesn't disappear when enable autoplay in Safari's preferences

### ISSUE THREAD

**Issue by Mikeks81** [video-react/video-react#55]
Safari 11 autoplay + bigPlayButton - doesn't disappear when enable autoplay in Safari's preferences.
I have a video-react player that has autoplay enabled and a bigPlaybutton. In Safari 11 they now block players attempting to autoplay. However, a user can allow certain sites to autoplay by enabling autoplay in the Safari preferences on a per website basis. When it is enabled and you refresh the page the video-react player will autoplay however the bigPlayButton does not disappear until you pause and play again. 

I know this is just hidden by CSS ( so i have a hacky solution to get around this on my app ) but it looks like the containing div is getting the 'video-react-has-started' class that hides the bigPlayButton when the video starts autoplaying. 

- version `#0.8.8`
- browser: `Safari 11.0`

### Expected behaviour
BigPlayButton should disappear

### Actual behaviour
Video plays with the bigPlayButton over the video until you press pause and play.

**Comment by JimLiu** [comment]
Hi @Mikeks81 
Sorry for late reply, I tried to reproduce that from my local with Safari 11.0.1 + v0.8.9, it can be hidden.

**Comment by mondaychen** [comment]
I'm closing all issues before 2018. If you can still observe the same problem, please re-report it. Thank you!
