### ISSUE TITLE
Error heroku deployment

### ISSUE THREAD

**Issue by kurtgee6** [video-react/video-react#56]
### Issue description

 'was loaded over HTTPS, but requested an insecure stylesheet 'http://video-react.js.org/assets/video-react.css'

### What happened

It works fine on the localhost server but when I deploy it to heroku...I get the error listed above. 

Example with picture

<img width="1407" alt="screen shot 2017-11-01 at 9 30 16 pm" src="https://user-images.githubusercontent.com/25759099/32305434-ea38d414-bf4b-11e7-8c6c-646bd524d1fe.png">

<img width="501" alt="screen shot 2017-11-01 at 9 31 17 pm" src="https://user-images.githubusercontent.com/25759099/32305462-1392304e-bf4c-11e7-889f-316ec6ca146c.png">

<img width="815" alt="screen shot 2017-11-01 at 9 33 23 pm" src="https://user-images.githubusercontent.com/25759099/32305517-625bad22-bf4c-11e7-8b94-ee49a9d48bd4.png">

**Comment by JimLiu** [comment]
From the error message, it looked like you link the css using `http://`, try to change it to `https://`, or put the css file into your own assets directory.

**Comment by kurtgee6** [comment]
Thanks @JimLiu but I actually just solved the issue. Instead of _using_...

<link rel="stylesheet" href="https://video-react.github.io/assets/video-react.css" />

I **imported** @import "~video-react/styles/scss/video-react"; to my file

and when I deployed it to Heroku, it knew to read it as that.
