### ISSUE TITLE
using yarn instead of npm

### ISSUE THREAD

**Issue by anthonyjoeseph** [video-react/video-react#58]
### Issue description

when I try to install 'video-react' using yarn instead of npm, the server crashes. Since I've been using yarn for the rest of my project, using 'npm install' per the readme causes npm to crash. 

- version `react 15.5.4`
- browser: `chrome-62`

### Steps to reproduce

1. yarn add video-react react react-dom redux
2. yarn start

### Expected behaviour
my website should load same as before I added the dependencies

### Actual behaviour
This is output by the react server - 

TypeError: Cannot read property '0' of undefined
  
  - ExternalModuleFactoryPlugin.js:19 
    [start-oliver]/[webpack]/lib/ExternalModuleFactoryPlugin.js:19:40
  
  - NormalModuleFactory.js:159 
    [start-oliver]/[react-scripts]/[webpack]/lib/NormalModuleFactory.js:159:3
  
  - Tapable.js:75 NormalModuleFactory.applyPluginsAsyncWaterfall
    [start-oliver]/[tapable]/lib/Tapable.js:75:69
  
  - NormalModuleFactory.js:144 NormalModuleFactory.create
    [start-oliver]/[react-scripts]/[webpack]/lib/NormalModuleFactory.js:144:8
  
  - Compilation.js:356 Compilation.process [as _addModuleChain]
    [start-oliver]/[react-scripts]/[webpack]/lib/Compilation.js:356:16
  
  - Compilation.js:424 Compilation.process [as addEntry]
    [start-oliver]/[react-scripts]/[webpack]/lib/Compilation.js:424:7
  
  - SingleEntryPlugin.js:24 Compiler.compiler.plugin
    [start-oliver]/[webpack]/lib/SingleEntryPlugin.js:24:16
  
  - Tapable.js:107 Compiler.applyPluginsParallel
    [start-oliver]/[tapable]/lib/Tapable.js:107:14
  
  - Compiler.js:394 Compiler.compile
    [start-oliver]/[react-scripts]/[webpack]/lib/Compiler.js:394:7
  
  - Compiler.js:203 Compiler.runAsChild
    [start-oliver]/[react-scripts]/[webpack]/lib/Compiler.js:203:7
  
  - compiler.js:70 
    [start-oliver]/[html-webpack-plugin]/lib/compiler.js:70:19
  
  - compiler.js:69 Object.compileTemplate
    [start-oliver]/[html-webpack-plugin]/lib/compiler.js:69:10
  
  - index.js:47 Compiler.<anonymous>
    [start-oliver]/[html-webpack-plugin]/index.js:47:40

### Demo
N/A

**Comment by JimLiu** [comment]
I don't think that's a problem of video-react, I didn't see any error relates to video-react from your post.
