### ISSUE TITLE
Controlling Play/Seek & Accessing Props from Outside Component

### ISSUE THREAD

**Issue by paolavness** [video-react/video-react#6]
Hi there,
This is a great component! So great to see a high quality component using react with redux. 

I need to be able to control the Player from components outside of the Player. I was expecting to have access to the Player state and props, but looks like they're not available?

For example, I have a playlist of snippets from a **single** video source. I want to be able to click on the a playlist item and play this snippet - ie, need to be able seek to this snippet in Player and play it. I also need to be able to access the currentTime, Duration and other props, in order to manipulate my playlist snippets.

I installed via NPM, am using chrome browser, and redux-logger to track actions and state - nothing is coming up in action and state when using default controls with <Player>...</Player>.

Thank - you!
Paola

**Comment by JimLiu** [comment]
@paolavness 
Yes, I just found I missed some apies for the Player component, I'll add it in next version.
But if you'd like to control in the current version, you could use property or method to seek.

https://video-react.github.io/components/player/

**I didn't test it, please let me know if there is any problem.**

1. Using property to start from 60s
```jsx
        <Player ref="player" autoPlay startTime={60}>
          <source src={this.state.playerSource} />
        </Player>
```

2. Using method
```jsx
        <Player ref="player" autoPlay>
          <source src={this.state.playerSource} />
        </Player>
```
```js
this.refs.player.video.seek(60); 
// I'll add `seek` api for the Player component next release, 
// but you could access the `seek` method from `Video` component direclty so far
```

**Comment by paolavness** [comment]
@JimLiu 
This is great, thank you for the quick response, I'll give it a try!
How about accessing the current playing time? This quite critical for my app, alongside the currently playing time.
Thanks again!

**Comment by paolavness** [comment]
Alright! And I can get the currentTime via the manager, that's great!
Thanks again for the quick response. I really appreciate. I'll be dropping my current video player to use this one instead. 👍 👍 👍

**Comment by JimLiu** [comment]
@paolavness 
Check the new example: 
https://video-react.github.io/components/player/
