### ISSUE TITLE
npm warnings with react v16

### ISSUE THREAD

**Issue by tomaswitek** [video-react/video-react#60]
### Issue description

- version `#0.8.10`

I am getting npm warnings when installing dependencies with newest version of react.

### Steps to reproduce

1. use react v16
2. npm install

### Expected behaviour
No warnings

### Actual behaviour
I am getting these two warnings:
warning "video-react@0.8.10" has incorrect peer dependency "react@^15.0.0".
warning "video-react@0.8.10" has incorrect peer dependency "react-dom@^15.0.0".

**Comment by JimLiu** [comment]
fixed in 0.9.0
