### ISSUE TITLE
video-react-waiting not show

### ISSUE THREAD

**Issue by myuanyuan** [video-react/video-react#62]
### Issue description
video-react-waiting can not play in IE 11 ,when i use Mac it is ok, but it cant play when i use win

- version #0.8.5
- browser: IE11

**Comment by JimLiu** [comment]
will fix it soon

**Comment by myuanyuan** [comment]
browser  ie11.0.20 in win7. thanks

**Comment by JimLiu** [comment]
@myuanyuan 
Couldn't reproduce that, do you have more details? like error message

**Comment by JimLiu** [comment]
Could you try v0.9.2?
