### ISSUE TITLE
When Video Loading, LoadSpinner not visible, BigPlay is visible

### ISSUE THREAD

**Issue by paolavness** [video-react/video-react#63]
Hi there, hope this finds you well

### Issue description
I have users loading long videos - 45 minutes to 1.5hrs. When the video is still loading, the BigPlayButton appears & user can click it. The LoadSpinner does not appear. Because the video is not ready to play, an error occurs

- version `#0.8.9`
- browser: `Chrome, Firefox, Safari`

### Steps to reproduce issue
Just load with an mp4that takes a along time to load and hit BigPlayButton. Make sure you have <LoadingSpinner /> 

### Expected behaviour
LoadingSpinner should appear until video is ready to be played, then BigPlayButton should replace it

### Actual behaviour
BigPlayButton appears immediately AND is ready for user to click on it.

--
Thank you,
Paola

**Comment by JimLiu** [comment]
Do you have the error message from console log?

**Comment by paolavness** [comment]
`The play() request was interrupted by a call to pause()`. This is also triggered tho when a user then uses the back() button. Note also tho that we have `autoPlay=false`, startTime=0` and           `preload="auto"`

**Comment by JimLiu** [comment]
@paolavness 
Do you have a sample mp4 url for testing?

**Comment by paolavness** [comment]
@JimLiu Thank you for looking into this. I've been using standard tests like the ones included in your docs. If you clear cache and then limit the network in DevTools to something like `Slow 3G`, this will replicate the issue of the BigPlayButton appearing before ready to play, instead of the LoadingSpinner.

**Comment by JimLiu** [comment]
@paolavness 
Couldn't reproduce that

**Comment by gusnips** [comment]
+1
```javascript
<Player
            ref="player"
            autoPlay={true}
            controls={true}
            playsInline={true}
            fluid={true}
            preload="metadata"
            src={"/api/watch/slowFile"}
            type={type}
            >
              <LoadingSpinner />
          </Player>
```

**Comment by JimLiu** [comment]
Could you fork this demo https://codesandbox.io/s/2v95wlpvjj and give me a sample can reproduce this issue?

**Comment by gusnips** [comment]
https://codesandbox.io/s/p2k43o82pm
My example is not 100% accurate because the video takes a long time to load first run, instead of not having a source, but the end result is the same
In my case, what I end up doing as a workaround is:
```js
componentDidMount(){
  setTimeout(function(){
   //it's not playable yet because it's loading but 'play' removes the big play button
   this.refs.player.play()
  },100)
}
```

**Comment by gusnips** [comment]
https://codesandbox.io/s/vy66lz8p07
a more precise example, even though it only takes a couple seconds to load you can see the big play button, and if you uncomment the setTimeout function it does work
I could help investigate the issue as do a PR as soon as i`m back working on this
Anyway, good job doing this player, thanks for the work put into it
