### ISSUE TITLE
IE 11 crashes with "SCRIPT16385: Not implemented" error when video-react sets preload attribute

### ISSUE THREAD

**Issue by joel-s** [video-react/video-react#65]
### Issue description

- version: Video-React `#0.9.2`
- browser: Internet Explorer 11.0.9600.17416 on Windows Server 2012 R2

### Steps to reproduce issue

1. Instantiate the Player component by rendering as follows ("/api/get-video/13/" is an API that returns a short video file):
```
    <Player src={`/api/get-video/13/`}>
      <ControlBar>
        <CurrentTimeDisplay order={4.1} />
        <TimeDivider order={4.2} />
        <PlaybackRateMenuButton
          rates={[5, 2, 1, 0.5, 0.1, 0.05, 0.02, 0.01]}
          order={7.1}
        />
      </ControlBar>
    </Player>
```
2. View the component in IE 11

### Expected behaviour
The video player would appear and work fine, except for not supporting seeking (since the video source is not a local file or streaming connection). This is what happens in Google Chrome.

### Actual behaviour
The browser window crashes and displays a blank page. Debugging in developer tools shows that the crash is due to a "SCRIPT16385: Not implemented" error when video-react sets the "preload" attribute to "auto"

### Demo
A sample page to show what happens in Internet Explorer when the preload attribute is set:
http://stylebites.de/fp5/preload.html

**Comment by joel-s** [comment]
This also happens without the ControlBar customization. The line in the babel/webpack bundle that throws the "Not implemented" exception is:
```
      node.setAttribute(name, '' + value);
```
Where name is "preload" and value is "auto".

**Comment by JimLiu** [comment]
Test good from my side
it might be broken by other code.


![image](https://user-images.githubusercontent.com/648674/33865886-5bba97e4-deb9-11e7-9b8b-2486249dac28.png)


```jsx
import React, { Component } from 'react';

import { Player, ControlBar, CurrentTimeDisplay, PlaybackRateMenuButton, TimeDivider  } from 'video-react';

import logo from './logo.svg';
import './App.css';
import "../node_modules/video-react/dist/video-react.css";

class App extends Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
        <Player src={`http://stylebites.de/fp5/ESS_ad_2012.mp4`}>
          <ControlBar>
            <CurrentTimeDisplay order={4.1} />
            <TimeDivider order={4.2} />
            <PlaybackRateMenuButton
              rates={[5, 2, 1, 0.5, 0.1, 0.05, 0.02, 0.01]}
              order={7.1}
            />
          </ControlBar>
        </Player>
      </div>
    );
  }
}

export default App;

```

**Comment by JimLiu** [comment]
test url: https://codesandbox.io/s/2v95wlpvjj

**Comment by joel-s** [comment]
Hi Jim,
 
Thanks for the speedy reply!
 
Visiting that URL, I get another Not Implemented error. This time I’m not able to set a breakpoint and debug it to find out what property is causing the crash, since the code is running in an eval().  I tried turning on “break on every exception” but after skipping through about 30 harmless exceptions, I gave up on that approach. (Maybe there’s some way to set a breakpoint in the eval, but I don’t know how to do it.)
 
Here’s the stack trace:
               
 
 
DOMPropertyOperations.setValueForProperty (eval
code:3677:7
 
 
setInitialDOMProperties (eval
code:5985:7
 
 
ReactDOMFiberComponent.setInitialProperties (eval
code:6151:5
 
 
finalizeInitialChildren (eval
code:16917:5
 
 
completeWork (eval
code:10923:15
 
 
completeUnitOfWork (eval
code:12481:7
 
 
performUnitOfWork (eval
code:12580:7
 
 
workLoop (eval
code:12682:11
 
 
callCallback (eval
code:1299:9
 
 
Thanks again for your help.
 
If you have any suggestions/requests for me, I’d be happy to hear from you.
- Joel

**Comment by joel-s** [comment]
@JimLiu 
I tried it and got the same error. That at least rules out the editor as the source of the problem. Let me know if a screen shot or any other information would be helpful.

**Comment by JimLiu** [comment]
@joel-s 
I just noticed that you tested that on Windows Server 2012 R2, I tested from window 7, it might has problems with window server, and I couldn't get any useful information from your error message.

Sorry for that it couldn't support all the browsers and OS.

**Comment by joel-s** [comment]
@JimLiu
Thanks for your response. As far as not having useful information from my error message, the root cause / solution seemed fairly clear to me, and I tried to present it in the original error report and my 1st comment. Internet Explorer doesn't support the **preload** attribute for videos, and on Windows Server 2012 it throws a NotImplementedError if an attempt is made to set it. Would it be fairly easy to not set the preload attribute if the browser is IE (IE will never support "preload" for videos).

**Comment by JimLiu** [comment]
@joel-s sound great!

Thanks
