### ISSUE TITLE
net::ERR_SPDY_PROTOCOL_ERROR when source change

### ISSUE THREAD

**Issue by netfull95** [video-react/video-react#67]
#- version 0.9.3
- browser: chrome Version 63.0.3239.108

I have an error when change source. it not happen for all video. 

<img width="532" alt="screen shot 2018-01-04 at 14 53 40" src="https://user-images.githubusercontent.com/22925962/34554509-cd99f7ca-f15f-11e7-8d8e-321f6afd53ab.png">

this source is still work.
`https://video.xx.fbcdn.net/v/t42.3356-2/26565480_1730360623704705_5454266559966734460_n.mp4/video-1515052338.mp4?vabr=178907&oh=dfc98331b1950ec5da7cd6be230e144c&oe=5A5070DE&dl=1`

my code:
```
<Player
            poster={attachment && attachment.url || null}
            ref="player"
            playsInline
            autoPlay
          >
            <BigPlayButton />
            <source src={source}/>
            <ControlBar autoHide={true}/>
          </Player>

```

```
loadedSource = response.attachments[playAtIdx] && response.attachments[playAtIdx].video_data && response.attachments[playAtIdx].video_data.url;
              this.setState({source: loadedSource});
              this.refs.player.load();
```

**Comment by JimLiu** [comment]
That looks liked a nginx problem:
https://stackoverflow.com/questions/33867014/what-mean-err-spdy-protocol-error-in-nginx
