### ISSUE TITLE
How do I set the video to not play when the screen is clicked?

### ISSUE THREAD

**Issue by xunina** [video-react/video-react#69]
### Steps to reproduce issue
1.click the screen  
2.The video starts playing ，the control bar appears

### Expected behaviour
The video does not play when I click on the screen, the control bar appears

###
How should I write code?

**Comment by JimLiu** [comment]
That's a feture need to be added.

But you can simpley disable the `Shortcut` component to disable it.
```
    <Player src="https://media.w3.org/2010/05/sintel/trailer_hd.mp4">
      <Shortcut disabled />
    </Player>
```

**Comment by xunina** [comment]
At the same time, I need to get video click events and do some of my own handling,Is there any solution for this problem?

**Comment by JimLiu** [comment]
Yes, you can

Write your own component, put it inside the <Player>, like this:
https://video-react.js.org/customize/customize-component/

It's similar with BigPlayButton
https://github.com/video-react/video-react/blob/master/src/components/BigPlayButton.js

**Comment by xunina** [comment]
I wrote one of my own components, but it's located below Video, and I used z-index to position it above the Video.     BigPlayButton at the top of the video and did not use z-index,What is the reason for this?

**Comment by JimLiu** [comment]
@xunina 
The style could be overwritten by your own css.

**Comment by xunina** [comment]
I just tried it，It is the "order" to play a role.

```
	<Video
        ref={(c) => {
          this.video = c;
          this.manager.video = this.video;
        }}
        key="video"
        order={0.0}
        {...fullProps}
      />,
       <BigPlayButton
        key="big-play-button"
        order={4.0}
        {...props}
      />,
```
Then I wrote the custom component's order is 3.5, and then it is between \<Video> and \<BigPlayButton>

**Comment by xunina** [comment]
So far, this problem has been solved,   thank you, 谢谢
