### ISSUE TITLE
support for ipad/pad?

### ISSUE THREAD

**Issue by xunina** [video-react/video-react#70]
### Issue description

- ipad version：10.3.2（14F89）  ； model:ME279CH/A
- browser: `safari`
- MI pad: android ：4.4.4KTU84P  MUUI：MIUI8.5|stable
- browser: `default browser`

### Steps to reproduce issue
1. open this link: https://video-react.js.org/components/player/
2. Move the screen to the video

### Steps to reproduce
- ipad
Buffered video is very slow，After buffering can be smoothly played
- MI pad
Buffered video is very slow，buffer 10s play 2s

### Expected behaviour
A reasonable buffer time

### Actual behaviour
Compared with the phone and the computer is very slow

Do not support pad/ipad? If not, why is this situation?

**Comment by xunina** [comment]
Because the software in the future to use pad, so considering this is not good for pad support

**Comment by JimLiu** [comment]
I don't think that's a problem caused by this component.
