### ISSUE TITLE
The video is above the customize component

### ISSUE THREAD

**Issue by xunina** [video-react/video-react#71]
### Issue description

- version `0.9.4`
- browser: `phone browser`

### Steps to reproduce issue
1.Set the phone is vertical screen
2.Set video horizontal screen play

### Steps to reproduce
1.Click BigPlayButton
2.The video starts playing

### Expected behaviour
customize components are located above the video

### Actual behaviour
customize components are located under the video
![image](https://user-images.githubusercontent.com/16541268/34772166-170ee564-f642-11e7-862e-4535b619038f.png)

1.When I set the phone screen to auto rotate and the video horizontal screen play，
 I get the expected result.      customize components are located above the video

2.When I set the phone screen vertical screen and the video horizontal screen play，I got the result above.   Custom components are located under the video。 How to solve this problem

**Comment by xunina** [comment]
![image](https://user-images.githubusercontent.com/16541268/34826245-ca4e0794-f710-11e7-9d88-e787aa471345.png)
as the picture shows,
Horizontal screen more than a vertical screen box style， Custom components are located under the video;
When i added the style that arrow points to, customize components are located above the video.

**Comment by JimLiu** [comment]
You can control them by css style

**Comment by xunina** [comment]
When I set the CSS to the <player>, it did not work.
I tested in the browser：
1.   set transform by class,  Custom components are located under the video;
![image](https://user-images.githubusercontent.com/16541268/34860481-a710335a-f798-11e7-8c04-7cc590937dd0.png)

2. set transform by element.style, customize components are located above the video.
![image](https://user-images.githubusercontent.com/16541268/34860537-22d432ca-f799-11e7-9c8b-4739565ebb67.png)

I can not set this directly in the my project, it should be set in the video-react.

**Comment by xunina** [comment]
The problem has been solved， thanks ，谢谢
```
componentDidMount () {
    const thisVideo: HTMLVideoElement = this.video.video.video
    thisVideo.style.transform = 'rotate(0deg)'
  }
```

**Comment by xunina** [comment]
this.video is <Player>

**Comment by xunina** [comment]
this.video is \<Player>

**Comment by xunina** [comment]
This method is only valid for Android
