### ISSUE TITLE
BigPlayButton doesn't work 

### ISSUE THREAD

**Issue by JoeyKo** [video-react/video-react#72]
### Issue description

- version `#0.9.3`
- browser: `Chrome-63.0.3239.132`
- mac

### Steps to reproduce

1. import BigPlayButton
2. set `position` to `center`
3. no change

**Comment by xunina** [comment]
* version #0.9.3
* browser chrome-63.0.3239.132
* mac

code：
```
<BigPlayButton position="center"/>
```

result: BigPlayButton is displayed in the center， You check the code again

**Comment by JimLiu** [comment]
@JoeyKo 
Could you show me an example from codesandbox?
https://codesandbox.io/s/2v95wlpvjj

**Comment by JoeyKo** [comment]
@JimLiu Thanks for the reply. I put `BigPlayButton ` in `ControlBar`, So it didn't work.
