### ISSUE TITLE
PlayToggle click causes full page refresh

### ISSUE THREAD

**Issue by mallorybulkley** [video-react/video-react#73]
### Issue description

- version `#0.9.3`
- browser: `chrome-63.0.3239.132`

### Steps to reproduce

1. play video using large play button
2. attempt to pause by clicking on PlayToggle button in corner
OR
1. play video using large play button
2. pause video by clicking on video
3. attempt to play by clicking on PlayToggle button in control bar

### Expected behaviour
it should play/pause

### Actual behaviour
forces a full refresh of the entire page.

My code is just: ```          <Player
            width={470}
            height={264}
            poster={video.thumbnail.url}
            src={video.url}
          />```

**Comment by JimLiu** [comment]
Couldn't be reproduced

**Comment by mallorybulkley** [comment]
FYI: The issue was that my Player was inside of a <form> and the <button> was causing the form to be submitted, which was triggering the refresh. I've got it working for me now, but video-react should probably be preventDefaulting on the buttons.

**Comment by chasemaier** [comment]
Should be resolved by https://github.com/video-react/video-react/pull/92.
