### ISSUE TITLE
Version Question - is 0.9.4 stable?

### ISSUE THREAD

**Issue by paolavness** [video-react/video-react#75]
Hello, hope this finds you well.

Home video-react home page says says latest version is 0.9.4. However, git Releases page has last update on Nov 15, 2017, to v0.8.10, which is also what I get when `yarn upgrade`ing. Is it possible to get v0.9.4 updates via npm or yarn, or are these not stable?

Thank you,
Paola

**Comment by JimLiu** [comment]
Sorry, I forgot to create a tag for that!
