### ISSUE TITLE
Local File Loading - Help needed

### ISSUE THREAD

**Issue by freshwuzhere** [video-react/video-react#76]
### Local File Loading

- version `#0.9.4`
- browser: `Safari-11.0.2`

### Call local file to play

1. added Webpack url-loader which generates local (127.0.0.1 url)
2. file either isn't found or unplayable - icon barred playicon displayed greyed out

### Expected behaviour
File of local source would play like web based file

### Actual behaviour
doesn't play

### Demo
unable since requires local file.

**Comment by JimLiu** [comment]
@freshwuzhere 
Does html5 video element support local file?

**Comment by freshwuzhere** [comment]
According to

 [https://stackoverflow.com/questions/8885701/play-local-hard-drive-video-file-with-html5-video-tag](url) 

It does.......

**Comment by JimLiu** [comment]
Sorry that's out of video-react's control

**Comment by aswincsekar** [comment]
you dont need webpack url-loader, lets say you have a input to select the local file like this
```
<form id="videoFile">
                      <input
                        type="file"
                        name="video"
                        multiple="false"
                        onChange={e => {
                          this.handleVideoLoad(e);
                        }}
                      />
                    </form>
```
then within this.handleVideoLoad, get the file input as url
```
handleVideoLoad(e) {
    console.log(e.target.files);
    let files = e.target.files;
    if (files.length === 1) {
      let file = files[0];
      this.setState({
        videoFileURL: URL.createObjectURL(file),
        videoFileObject: file
      });
    }
  }
```
the use the URL created from the object as src to video-react like this
```
<Player
                      ref="player"
                      src={videoFileURL}
                    >
                      <ControlBar disabled />
                    </Player>
```
This will play the local file

**Comment by freshwuzhere** [comment]
That works perfectly and seem as if much simpler than we pack!  Thank you!

**Comment by whitepotato** [comment]
Line 52:  Parsing error: Unexpected token, expected ","

  50 | 
  51 | 
> 52 |             handleVideoLoad(e) {
     |                                ^
  53 |             console.log(e.target.files);
  54 |             let files = e.target.files;
  55 |             if (files.length === 1) {
