### ISSUE TITLE
autoplay on Safari and Chrome browser from mobile (iPhone 7 and above) not working

### ISSUE THREAD

**Issue by uhdang** [video-react/video-react#79]
### Issue description

- version `#0.9.4.`
- browser: mobile `Safari + Chrome` from iPhone 7 +

### Steps to reproduce issue
Player component with autoPlay props passed down doesn't autoplay in safari

### Steps to reproduce
- Try playing a video with autoPlay props on Safari i.e. https://video-react.js.org/components/control-bar/

### Expected behaviour
- video should autoplay

### Actual behaviour
- video remains standby

**Comment by uhdang** [comment]
Okay, just found out Apple blocked autoplay.
Seeing this isn't related issue to this library, closing this issue.

ref: https://techcrunch.com/2017/06/05/auto-play-block/

**Comment by zhangkuiworld** [comment]
> Okay, just found out Apple blocked autoplay.
> Seeing this isn't related issue to this library, closing this issue.
> 
> ref: https://techcrunch.com/2017/06/05/auto-play-block/

The article says it blocked in Mac, but iPhone doesn't work either, why ?

**Comment by mondaychen** [comment]
@zhangkuiworld to my knowledge, Safari for iPhone blocked auto-play even earlier
