### ISSUE TITLE
Allow the hosting App to provide the store for the player to use

### ISSUE THREAD

**Issue by rart** [video-react/video-react#80]
### Description

Currently, the player's store creation and the store itself is completely encapsulated in the "Manager".

This disallows for the App and the Player to use the same store. Additionally, subscribing to the player's store through `subscribeToPlayerStateChange` doesn't provide the unsubscribe function.

I suggest the Player component reading the `context` (e.g. using `Provider` from `react-redux`) and/or `props` to see if there is a store provided and use that one: the hosting app could mix/register the reducers from this lib together with the rest of app reducers and pass the store instance. If the store is not provided it would still create it's own encapsulated store.

The other cool thing about this, is that then the app could interact with the player and specifically with the store as the architecture suggests: through (store) messages. Also, if the main app is using the redux dev tools, developers would benefit from the visibility of all the messages flowing through the main app's store.

I'm happy to collaborate but want a formal green light from the maintainers to know the PR would indeed get merged. If the idea sounds good to you guys and want me to give it a go, if there's a preferred way to implement different from the suggested, please provide that too.

**Comment by JimLiu** [comment]
💚
