### ISSUE TITLE
QUESTION: How to attach a particular task to a control bar button?

### ISSUE THREAD

**Issue by UtkarshGupta-CS** [video-react/video-react#84]
### Issue description

- version `#0.9.4`
- browser: `Chrome-64`

### Description
So my question is `How to attach a particular task to a control bar button?`. I want to log each event like seek, play, pause etc. Is there any way I can do that?

> Sorry I couldn't find any chat channel so I made this issue.

**Comment by JimLiu** [comment]
If just one of the control bar button, you can write your own button, then add your logic.
Like this:
https://video-react.js.org/customize/customize-component/

Or wait for this PR: https://github.com/video-react/video-react/pull/81

Then you can subscribe the redux store.

**Comment by UtkarshGupta-CS** [comment]
I have created the custom component for now, after the PR I will subscribe to corresponding redux action. TY 💯
