### ISSUE TITLE
No way to use or replace native iOS controls

### ISSUE THREAD

**Issue by jmeyers91** [video-react/video-react#86]
### Issue description

The iOS player uses different UI elements (see the second screenshot in #82), but there's no clear way to interact with the controls. There appears to be an X close button, but I don't know how to add an press handler to it. And I can't add my own close button because as soon as the video begins playing on iOS, any fixed position elements I've placed above it disappear.

- version `#0.9.4`
- browser: `Cordova app on iOS (Safari?)`

### Steps to reproduce issue

My video wrapper component:

```
import styled from 'styled-components';
import { View } from 'shared/View';
import { Player } from 'video-react';
import * as Icons from 'shared/components/Icons';
import config from 'config';

export default class VideoOverlay extends View {
  render() {
    const { props, onClose } = this;

    return (
      <Root>
        <Player autoPlay playsInline={false}>
          <CloseButton onClick={onClose}/>
          <source src={`${config.server}${props.src}`}/>
        </Player>
      </Root>
    );
  }
}

const Root = styled.div`
  position: fixed;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  background-color: red;
  z-index: 100;
`;

const CloseButton = styled(Icons.CircleX).attrs({size: 25})`
  position: fixed;
  right: 10px;
  top: 10px;
  cursor: pointer;
  color: white;
  z-index: 10000;
`;
```

`CloseButton` is visible before the video begins playing, but disappears immediately after, and there doesn't appear to be any documentation for using or hiding these buttons:

<img width="238" alt="screen shot 2018-02-21 at 1 14 27 pm" src="https://user-images.githubusercontent.com/24255174/36505731-4022ca32-1709-11e8-9e01-537662dbf516.png">

**Comment by JimLiu** [comment]
@jmeyers91 
Did you have any online demo for this?

If you set `playsInline` as "true", it won't use iOS native controls for full screen, but it's not a real full screen.

**Comment by jmeyers91** [comment]
I don't have an online demo. I thought I tried `playsInline={true}`, but I can't remember. I'll try when I get a few. Do you have any plans to support customizing iOS native controls? If not, you can go ahead and close this issue.

**Comment by JimLiu** [comment]
@jmeyers91 
I think there is no way to customize iOS native controls.

You can also take a look at video.js https://videojs.com/

**Comment by jmeyers91** [comment]
Yeah it seemed like a bit of a stretch. I might be able to find a native solution. Anyway, thanks for getting back to me.
