### ISSUE TITLE
Cannot set width and height

### ISSUE THREAD

**Issue by wandonye** [video-react/video-react#91]
My codes of using the component:
```
<Player playsInline fluid={false} width={100} height={50}>
       <source src="https://media.w3.org/2010/05/sintel/trailer_hd.mp4"/>
</Player>
```
Following other posts, I tried
```
import "node_modules/video-react/dist/video-react.css";
```
and
```
import "video-react/dist/video-react.css";
```

Neither worked.
My folder structure is like this:

```
my_project/
--app/
----components/
----app.global.css
....
--node_modules/
```

Also tried adding 
```
@import "~video-react/styles/scss/video-react"; // or import scss
```
to  `app.global.css`. It then report error.

**Comment by wandonye** [comment]
This worked:

```
@import "~video-react/dist/video-react.css";
```

The readme file probably needs an update

**Comment by JimLiu** [comment]
I'll add the readme, thanks

**Comment by ArtixZ** [comment]
tried` import "video-react/dist/video-react.css";`  I'm having this issue.

**Comment by ArtixZ** [comment]
tried:
`import "video-react/dist/video-react.css";`
I'm having this issue.

**Comment by JimLiu** [comment]
@ArtixZ Did you get any error message?
