### ISSUE TITLE
Doesn't want to play my video on chrome but it work on Safari !!

### ISSUE THREAD

**Issue by sjollois** [video-react/video-react#94]
### Doesn't want to play my video on chrome but it work on Safari 

- version `last`
- browser: `chrome Version 64.0.3282.186` `safari 11.0.3` 

### Steps to reproduce issue

Here's my code that handles playing video:

```
import { Player, ControlBar, VolumeMenuButton, BigPlayButton } from 'video-react';
import video from '/Users/samueljollois/Documents/GitHub/NIELS/src/video/videoPresentation.m4v';
import "video-react/dist/video-react.css";
<Player>
              <muted true/>
              <source src={video} />
              <ControlBar>
                                    <VolumeMenuButton disabled />
              </ControlBar>
              <BigPlayButton position="center"/>
</Player>
```

### Expected behaviour

The video should work on both browsers

### Actual behaviour

The video work on safari but not on chrome

**Comment by JimLiu** [comment]
It looks like a problem with local video, it's out of the component's control.
