### ISSUE TITLE
How to disable the fullscreen option

### ISSUE THREAD

**Issue by acondarco** [video-react/video-react#95]
- version 0.9.4
- browser: All desktop browsers

Hi guys, hope you are great.

Please, I need to know a way to disable the fullscreen option for all desktop browsers.

Regards,

**Comment by JimLiu** [comment]
Did you mean the fullscreen button? you can disable it follow this document: https://video-react.js.org/customize/enable-disable-components/

**Comment by pirsquare** [comment]
If you want to completely disable full screen, you might also want to update shortcut component to overwrite `toggleFullscreen` method. 


```
// Disable full screen
class Shortcut extends BaseShortcut {
  constructor (props) {
    super(props);
  }
  toggleFullscreen = (player, actions) => {};
}
```

**Comment by mghayour** [comment]
also we can use :
```js
this.refs.player.actions.toggleFullscreen=()=>{console.log('prevent full screen video');};
```

**Comment by gabrielmoterani** [comment]
> also we can use :
> 
> ```js
> this.refs.player.actions.toggleFullscreen=()=>{console.log('prevent full screen video');};
> ```

Where do i apply this code?

**Comment by YardWill** [comment]
> > also we can use :
> > ```js
> > this.refs.player.actions.toggleFullscreen=()=>{console.log('prevent full screen video');};
> > ```
> 
> Where do i apply this code?

Set A React Ref on your player，and then use the code in componentDidMount or useEffect if you use hooks.

**Comment by GilbertMizrahi** [comment]
That works. But is there a way to remove the full-screen icon from the controls?

**Comment by papuruth** [comment]
This works for some videos only as I have used infinite scroll for rendering items and when the next page renders the ref attached to players are undefined. Is there any solution to disable it completely.

**Comment by jameszhou02** [comment]
If anyone is trying to do this in the future, here's what worked for me:

Create a ref:
`
const videoRef = useRef<any>(null); 
`

In the useEffect on render:
`
useEffect(() => {
  setPlayer(videoRef.current);
  videoRef.current.actions.toggleFullscreen = () => {
    console.log("prevent full screen video");
  };
}, []);
`

The player component:
`
<Player ref={videoRef} >
	{...children}
</Player>
`
