### ISSUE TITLE
Video source switching fails in Safari 10.2.1

### ISSUE THREAD

**Issue by rtcoms** [video-react/video-react#96]
### Issue description
replacing video doesn't reflect correctly in video player in Safari 10.1.2

- version `^0.9.4`
- browser: `Safari-10.1.2` (I've tested using browserstack)

### Steps to reproduce

1. step1
Open url https://video-react.js.org/components/player/ in safari 10.2.1 . Check example given in" Control the player" section
2. step2
Switch between bunny trailer, Sintel teaser and Test movie. Video playing in the player would be generally one step behind.
3. step3
Although if you select the video and then click load() and play(), then it works fine

### Expected behaviour
Same video should play in the player to which user has switched.

### Actual behaviour
Video playing in the player would be generally one step behind. 

I tried to use load() and play() explicitly in my implementation but it didn't work.

**Comment by JimLiu** [comment]
Sorry I could not produce that from my Safari Version 11.0.3 (13604.5.6).I suggest you try video.js https://github.com/videojs/video.js , it might have no this issue, and think about use video.js for your project.
