### ISSUE TITLE
Cannot read property 'paused' of undefined

### ISSUE THREAD

**Issue by jonaswindey** [video-react/video-react#99]
### Issue description

- version `#0.10.3`
- browser: `Chrome`

### Steps to reproduce

1. Fresh install to a project in Next.js

### Actual behaviour
When adding the component, following error is thrown:

```
Cannot read property 'paused' of undefined
TypeError: Cannot read property 'paused' of undefined
    at Player.render (/Users/jonas/Development/3nit/lexus-net/node_modules/video-react/src/components/Player.js:361:13)
```

It looks like it can't find the store in the getState() function. Could it possibly conflict with the Redux instance in my application?

**Comment by xavifuefer** [comment]
+1 same issue here. It looks like it's not able to find the player instance? maybe an issue with the `ref`

**Comment by JimLiu** [comment]
I'll take a look with that, thanks for your report

**Comment by JimLiu** [comment]
Fixed in 0.10.4

**Comment by xavierfuentes** [comment]
has it been released?

**Comment by JimLiu** [comment]
@xavierfuentes 
Yes, it released.

The previous version tried to get store from context instead of creating the store from video-redux's reducers.

The fix is video-react only get `store` instance from the property, not from context.
